---
title: "Create daummy raster for Berlin" ## name of your project
author: "Moritz Wenzler"                     ## your name(s)
date: "`r Sys.Date()`"                  ## current date
output:
  rmdformats::readthedown:
    code_folding: hide                  ## hide or show code by default?
    toc_depth: 3                        ## 3-level TOC
---

```{r setup, include=FALSE}
## You can ignore this chunk in most cases
## If you want to modify chunk options, you can do it here for all chunks or
## add the options in the repsective chunk header, e.g. `{r, message = FALSE}`
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE,
                      fig.width = 9, fig.height = 6, dpi = 500, 
                      retina = 1, fig.showtext = TRUE)
```

* **Research question:**
* **Study area:**
* **Data:** 


# Setup

```{r packages}
sapply(list("sf", "tidyverse", "raster", "ows4R"), 
       library, character.only = TRUE, logical.return = TRUE)

source(here("R", "download_fisbroker_metadata.R"))
```


# Data

```{r data}
berlin_district <- st_read(here("data-raw", "berlin", "berlin_districts_2020_3035", "berlin_districts_2020_3035.gpkg"))

ext_stud <- extent(berlin_district)

# esm for berlin N33E44, N33E45
esm_n33e44 <- raster::raster(paste("data-raw", "europe","european_settlement_2015_100m_3035", "a6f0feb612c7a0dbf8f6f0a795229ab065d15439", "ESM_BUILT_VHR2015CLASS_R2019_3035_N33E44_010m_v010", "ESM_BUILT_VHR2015CLASS_R2019_3035_N33E44_010m_v010", "Data", "ESM_BUILT_VHR2015CLASS_R2019_3035_N33E44_010m_v010.tif", sep = "/"))

esm_n33e45 <- raster::raster(paste("data-raw", "europe","european_settlement_2015_100m_3035", "a6f0feb612c7a0dbf8f6f0a795229ab065d15439", "ESM_BUILT_VHR2015CLASS_R2019_3035_N33E45_010m_v010", "ESM_BUILT_VHR2015CLASS_R2019_3035_N33E45_010m_v010", "Data", "ESM_BUILT_VHR2015CLASS_R2019_3035_N33E45_010m_v010.tif", sep = "/"))

esm_be <- merge(esm_n33e44, esm_n33e45) %>% 
  crop(berlin_district %>% st_buffer(1000))

esm_be[] <- NA

temp_ras_berlin <- esm_be

names(temp_ras_berlin) <- []

create_meta_raster(file = temp_ras_berlin,
                   name = "template_raster_berlin_10m",
                   epsg = "3035",
                   date = "2020",
                   units = NA,
                   descr = "template raster for Berlin in 10m resolution and in 3035 projection",
                   orig_source = NA,
                   data_source = NA,
                   d_down = NA,
                   mod = NA,
                   path = "data-proc/berlin",
                   folder = TRUE)

writeRaster(temp_ras_berlin, here("data-proc", "berlin", 
                                   "template_raster_berlin_10m_2020_3035",
                                   "template_raster_berlin_10m_2020_3035.tif"), overwrite=TRUE)

```


***

<details><summary>Session Info</summary>

```{r sessionInfo}
## DO NOT REMOVE!
## We store the settings of your computer and the current versions of the
## packages used to allow for reproducibility
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>
