---
title: "plots_hours"
author: "Aimara Planillo"
date: '2022-11-23'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(dplyr)
library(ggplot2)
library(scico)
```

# Plotting around the clock

## load data

Resting percentage of lynxes - example

```{r}
data <- read.csv("act_by_hour_example.csv")


# get percentages to plot averaged across days
data_pct <- data %>% 
  group_by(animals_id, hour) %>%   
  summarise(mean_pct = mean(pct_rest_hour), 
            sd_pct = sd(pct_rest_hour),
            name = unique(animals_name)) 


## additional data frame for plotting labels

# get totals
data2 <- data %>% 
  group_by(animals_id, date) %>%   
  summarise(total_rest = sum(pct_rest_hour)) %>% 
  group_by(animals_id) %>% 
  summarise(mean_rest = round(mean(total_rest),2))


  
dat_text <- data.frame(
  label = data2$mean_rest,
  animals_id = data2$animals_id) %>%
  mutate(animals_id = as.numeric(as.character(animals_id)))
```


```{r plot resting behaviour 1 ind - dark}
## ind 725
ind_tmp <- data_pct %>% 
  filter(animals_id == 1) %>% 
  mutate(hour_num = as.numeric(hour))

labels_tmp <- dat_text %>% 
    filter(animals_id == 1)

(plot_tmp <- ggplot(ind_tmp) +
    geom_col(aes(hour, mean_pct, fill = mean_pct), color = "grey70", width = 1) +
    coord_polar(start = 25) + # start at hour 25 to put the 0 on top
    theme_light() +
    ylab("percentage of resting time\n") +
    labs(title = paste0("Resting pattern ind ", labels_tmp$animals_id),  
         subtitle = paste0("Average daily resting time: ", labels_tmp$label, "%"), 
         fill = "Hourly percentage") +
    theme(title = element_text(size = 16, face = "bold"),
      axis.title = element_text(size = 14), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(colour = "white", size = 12),
      axis.text.y = element_text(colour = "grey20", size = 12),
      legend.title = element_text(size = 12),
      legend.text = element_text(size = 12),
      legend.background = element_rect(colour = "grey40", fill = "grey70"),
      legend.justification = c(0,1),
        panel.border = element_blank(),
        panel.grid = element_line(colour = "grey50"),
        panel.background = element_rect(fill = "grey40"), 
      plot.background = element_rect(fill = "grey80")) 
)
```

```{r plot resting behaviour 1 ind - light}
my_bilbao <- scico(10, alpha = NULL, begin = 0, end = 1, direction = 1, palette = "bilbao")
min(my_bilbao)
my_bilbao <- my_palette[-1]

(plot_light <- ggplot(ind_tmp) +
    geom_col(aes(hour, mean_pct, fill = mean_pct), color = NA, width = 0.95) +
    coord_polar(start = 25) +
    theme_light() +
    ylab("percentage of resting time\n") +
    scale_fill_gradientn(colours = rev(my_bilbao)) +
    labs(title = paste0("Resting pattern ind ", labels_tmp$animals_id),  
         subtitle = paste0("Average daily resting time: ", labels_tmp$label_2, "%"), 
         fill = "Daily percentage") +
    theme(title = element_text(size = 16, face = "bold"),
      axis.title = element_text(size = 14), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(colour = "black", size = 14),
      axis.text.y = element_text(colour = "grey20", size = 14),
      legend.title = element_text(size = 12, face = "bold"),
      legend.text = element_text(size = 12),
      legend.background = element_rect(colour = "grey90", fill = "grey90"),
      legend.justification = c(0,1),
        panel.border = element_blank(),
        panel.grid = element_line(colour = "grey70"),
        panel.background = element_rect(fill = "grey90"), 
      plot.background = element_rect(fill = "grey90")) 
)
```

```{r plot resting behaviour 1 ind - light blue}
(plot_lightblue <- ggplot(ind_tmp, aes(x = hour)) +
  geom_col(aes (y = mean_pct, fill = mean_pct), color = NA, width = 0.95) +
  coord_polar(start = 25) + # start at hour 25 to put the 0 on top
  scale_fill_scico(palette = "devon",
                   direction = -1, alpha = 1, begin = 0.5, end = 0.9) +
  theme_minimal() +
  ylim(-0.01, 0.8) + # the negative value controls the size of the inner circle
  labs(title = paste0("Resting pattern ind ", labels_tmp$animals_id),  
         subtitle = paste0("Average daily resting time: ", labels_tmp$label_2, "%"), 
         fill = "Daily percentage") +
  ylab("Percentage of time resting\n") +
  theme_light() +
  theme_minimal() +
  theme(title = element_text(size = 16, face = "bold"),
        axis.title = element_text(size = 14),
        axis.title.x = element_blank(),
        axis.text.x = element_text(colour = "black", size = 14),
        axis.text.y = element_text(colour = "grey20", size = 14),
        legend.title = element_text(size = 12, face = "bold"),
        legend.text = element_text(size = 12),
        legend.background = element_rect(colour = "ivory", fill = "ivory"),
        # legend.position = c(1.05, 1),
        legend.justification = c(0,1),
        panel.border = element_blank(),
        panel.grid = element_line(colour = "grey80", linetype = 1, size = 0.5),
        panel.background = element_rect(fill = "ivory", colour = "ivory"),
        plot.background = element_rect(fill = "ivory",  colour = "ivory"),
  )
)
```


```{r saving the plot}
# for saving
# ggsave(plot = plot_lightblue, 
#        filename = "Clock_PctDailyRest_ind1_light_blue.png",
#        dpi = 300, width = 8, height = 7)
```

```{r plot resting behaviour all ind - light}
data_pct
dat_text

my_palette <- scico(10, alpha = NULL, begin = 0, end = 1, direction = 1, palette = "bilbao")
my_palette
my_bilbao <- my_palette[-1]


ind_tmp <- unique(data_pct$animals_id)

for(i in 1:length(unique(ind_tmp))){
 
  data_tmp <- data_pct %>% 
    filter(animals_id == ind_tmp[i])
  labels_tmp <- dat_text %>% 
    filter(animals_id == ind_tmp[i])
  plot_tmp <- ggplot(data_tmp) +
    geom_col(aes(hour, mean_pct, fill = mean_pct), color = NA, width = 0.95) +
    coord_polar(start = 25) +
    theme_light() +
    ylab("percentage of resting time\n") +
    scale_fill_gradientn(colours = rev(my_bilbao)) +
    labs(title = paste0("Resting pattern ind ", ind_tmp[i]),  
         subtitle = paste0("Average daily resting time: ", labels_tmp$label_2, "%"), 
         fill = "Daily percentage") +
    theme(title = element_text(size = 16, face = "bold"),
      axis.title = element_text(size = 14), 
        axis.title.x = element_blank(),
        axis.text.x = element_text(colour = "black", size = 14),
      axis.text.y = element_text(colour = "grey20", size = 14),
      legend.title = element_text(size = 12, face = "bold"),
      legend.text = element_text(size = 12),
      legend.background = element_rect(colour = "grey90", fill = "grey90"),
      # legend.position = c(1.05, 1),
      legend.justification = c(0,1),
        panel.border = element_blank(),
        panel.grid = element_line(colour = "grey70"),
        panel.background = element_rect(fill = "grey90"), 
      plot.background = element_rect(fill = "grey90")) 
        # panel.background = element_rect(fill = "grey80")) 
  
  
  ## save the plots within the loop
  
  # ggsave(plot = plot_tmp, filename = paste0("Clock_PctDailyRest_resid_ind", ind_tmp[i], ".png"), 
  #      dpi = 300, width = 8, height = 7)

}
```