---
  title: "distance to open green areas raster" ## name of your project
author: "Moritz Wenzler"                     ## your name(s)
date: "`r Sys.Date()`"                  ## current date
output:
  rmdformats::readthedown:
  code_folding: hide                  ## hide or show code by default?
toc_depth: 3                        ## 3-level TOC
---
  
  ```{r setup, include=FALSE}
## You can ignore this chunk in most cases
## If you want to modify chunk options, you can do it here for all chunks or
## add the options in the repsective chunk header, e.g. `{r, message = FALSE}`
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE,
                      fig.width = 9, fig.height = 6, dpi = 500, 
                      retina = 1, fig.showtext = TRUE)
```

* **Research question:**
  * **Study area:**
  * **Data:** 
  
  
  # Setup
  
  ```{r packages}
sapply(list("sf", "tidyverse", "raster", "ows4R", "here", "fasterize"), 
       library, character.only = TRUE, logical.return = TRUE)

source(here("R", "download_fisbroker_metadata.R"))
```


# Data

```{r data}
berlin_district <- st_read(here("data-raw", "berlin", "berlin_districts_2020_3035", "berlin_districts_2020_3035.gpkg"))

temp_ras <- raster(here("data-proc", "berlin", "template_raster_berlin_10m_2020_3035", "template_raster_berlin_10m_2020_3035.tif"))

oga <- st_read(here("data-raw", "berlin", "open_green_areas_2020_3035", "open_green_areas_2020_3035.gpkg"))

oga$inter <- 1

oga_ras_10m <- fasterize::fasterize(sf = oga,
                                    raster = temp_ras,
                                    field = "inter")

plot(oga_ras_10m)

oga_ras_10m_dist <- raster::distance(oga_ras_10m)

plot(oga_ras_10m_dist)

oga_ras_10m_dist_mask <- raster::mask(x = oga_ras_10m_dist, 
                                      mask = berlin_district,
                                      updatevalue = NA
) 

plot(oga_ras_10m_dist_mask)

create_meta_raster(oga_ras_10m_dist_mask, 
                   name = "distance_to_open_green_areas_raster",
                   date = "2020",
                   epsg = "3035",
                   units = "distance in meter [m]",
                   descr = "created from open_green_areas_2020_3035",
                   source = here("data-raw", "berlin", "open_green_areas_2020_3035", "open_green_areas_2020_3035.gpkg"),
                   d_down = NA,
                   mod = "NAs inside Berlin borders where set to 0 %",
                   path = "data-proc/berlin",
                   folder = TRUE)

writeRaster(oga_ras_10m_dist_mask, here("data-proc", "berlin", "distance_to_open_green_areas_raster_2020_3035", "distance_to_open_green_areas_raster_2020_3035.tif"), overwrite = TRUE)
```


***
  
  <details><summary>Session Info</summary>
  
  ```{r sessionInfo}
## DO NOT REMOVE!
## We store the settings of your computer and the current versions of the
## packages used to allow for reproducibility
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>
  