---
  title: "open green areas raster" ## name of your project
author: "Moritz Wenzler"                     ## your name(s)
date: "`r Sys.Date()`"                  ## current date
output:
  rmdformats::readthedown:
  code_folding: hide                  ## hide or show code by default?
toc_depth: 3                        ## 3-level TOC
---
  
```{r setup, include=FALSE}
## You can ignore this chunk in most cases
## If you want to modify chunk options, you can do it here for all chunks or
## add the options in the repsective chunk header, e.g. `{r, message = FALSE}`
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE,
                      fig.width = 9, fig.height = 6, dpi = 500, 
                      retina = 1, fig.showtext = TRUE)
```

* **Research question:**
  * **Study area:**
  * **Data:** 
  
  
  # Setup
  
```{r packages}
sapply(list("sf", "tidyverse", "raster", "ows4R", "here", "fasterize"), 
       library, character.only = TRUE, logical.return = TRUE)

source(here("R", "download_fisbroker_metadata.R"))
```


# Data

```{r data}
berlin_district <- st_read(here("data-raw", "berlin", "berlin_districts_2020_3035", "berlin_districts_2020_3035.gpkg"))

temp_ras <- raster(here("data-proc", "berlin", "template_raster_berlin_10m_2020_3035", "template_raster_berlin_10m_2020_3035.tif"))

oga <- st_read(here("data-raw", "berlin", "open_green_areas_2015_3035", "open_green_areas_2015_3035.gpkg"))

temp_a <- crop(temp_ras, extent(c(xmin = xmin(temp_ras),
                                 xmax = (xmax(temp_ras)-(xmax(temp_ras)-xmin(temp_ras))/ 2)+5,
                                 ymin = (ymax(temp_ras)-(ymax(temp_ras)-ymin(temp_ras))/ 2)-5,
                                 ymax = ymax(temp_ras))))

temp_b <- crop(temp_ras, extent(c(xmin = (xmax(temp_ras)-(xmax(temp_ras)-xmin(temp_ras))/ 2)-5,
                                 xmax = xmax(temp_ras),
                                 ymin = (ymax(temp_ras)-(ymax(temp_ras)-ymin(temp_ras))/ 2)-5,
                                 ymax = ymax(temp_ras))))

temp_c <- crop(temp_ras, extent(c(xmin = xmin(temp_ras),
                                 xmax = (xmax(temp_ras)-(xmax(temp_ras)-xmin(temp_ras))/ 2)+5,
                                 ymin = ymin(temp_ras),
                                 ymax = (ymax(temp_ras)-(ymax(temp_ras)-ymin(temp_ras))/ 2))+5))

temp_d <- crop(temp_ras, extent(c(xmin = (xmax(temp_ras)-(xmax(temp_ras)-xmin(temp_ras))/ 2)-5,
                                 xmax = xmax(temp_ras),
                                 ymin = ymin(temp_ras),
                                 ymax = (ymax(temp_ras)-(ymax(temp_ras)-ymin(temp_ras))/ 2))+5))

# template a
values(temp_a) <- 1
temp_poly <- rasterToPolygons(temp_a)

st_crs(oga) <- crs(temp_a)

oga_inter_a <- st_intersection(oga %>% st_crop(temp_poly %>% as("sf")), temp_poly %>% as("sf"))
oga_inter_a <- oga_inter_a %>% 
  mutate(area = as.numeric(st_area(.))) %>% 
  st_cast("POLYGON")

oga_ras_10m_a <- fasterize::fasterize(sf = oga_inter_a,
                                    raster = temp_a,
                                    field = "area")

# template b
values(temp_b) <- 1
temp_poly <- rasterToPolygons(temp_b)

st_crs(oga) <- crs(temp_b)

oga_inter_b <- st_intersection(oga %>% st_crop(temp_poly %>% as("sf")), temp_poly %>% as("sf"))
oga_inter_b <- oga_inter_b %>% 
  mutate(area = as.numeric(st_area(.))) %>% 
  st_cast("POLYGON")

oga_ras_10m_b <- fasterize::fasterize(sf = oga_inter_b,
                                    raster = temp_b,
                                    field = "area")

# template c
values(temp_c) <- 1
temp_poly <- rasterToPolygons(temp_c)

st_crs(oga) <- crs(temp_c)

oga_inter_c <- st_intersection(oga %>% st_crop(temp_poly %>% as("sf")), temp_poly %>% as("sf"))
oga_inter_c <- oga_inter_c %>% 
  mutate(area = as.numeric(st_area(.))) %>% 
  st_cast("POLYGON")

oga_ras_10m_c <- fasterize::fasterize(sf = oga_inter_c,
                                    raster = temp_c,
                                    field = "area")

# template d
values(temp_d) <- 1
temp_poly <- rasterToPolygons(temp_d)

st_crs(oga) <- crs(temp_d)

oga_inter_d <- st_intersection(oga %>% st_crop(temp_poly %>% as("sf")), temp_poly %>% as("sf"))
oga_inter_d <- oga_inter_d %>% 
  mutate(area = as.numeric(st_area(.))) %>% 
  st_cast("POLYGON")

oga_ras_10m_d <- fasterize::fasterize(sf = oga_inter_d,
                                    raster = temp_d,
                                    field = "area")

oga_ras_10m <- raster::merge(oga_ras_10m_a, oga_ras_10m_b, oga_ras_10m_c, oga_ras_10m_d)

oga_ras_10m[is.na(oga_ras_10m)] <- 0

oga_ras_10m_mask <- raster::mask(x = oga_ras_10m, 
                                      mask = berlin_district,
                                      updatevalue = NA
) 

plot(oga_ras_10m_mask)

create_meta_raster(oga_ras_10m_mask, 
                   name = "open_green_areas_raster_10m",
                   date = "2020",
                   epsg = "3035",
                   units = "percentage green area per cell",
                   descr = "created from open_green_areas_2020_3035",
                   orig_source = read.csv(here("data-raw", "berlin", "berlin_districts_2020_3035", "metadata_berlin_districts_2020_3035.csv"), header = TRUE)$source,
                   data_source = here("data-raw", "berlin", "open_green_areas_2020_3035", "open_green_areas_2020_3035.gpkg"),
                   d_down = NA,
                   mod = "NAs inside Berlin borders where set to 0 %",
                   path = "data-proc/berlin",
                   folder = TRUE)

writeRaster(oga_ras_10m_mask, here("data-proc", "berlin", "open_green_areas_raster_10m_2020_3035", "open_green_areas_raster_2020_10m_3035.tif"), overwrite = TRUE)
```

***
  
  <details><summary>Session Info</summary>
  
  ```{r sessionInfo}
## DO NOT REMOVE!
## We store the settings of your computer and the current versions of the
## packages used to allow for reproducibility
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>
  