---
date: "`r Sys.Date()`"
output: 
    distill::distill_article:
        highlight: kate      ## styling of code
        code_folding: false  ## if `true` you can expand and shrink code chunks
        toc: true            ## if `true` adds a table of content
        toc_depth: 2         ## level to be displayed in the table of content
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      dev = "ragg_png", fig.width = 9, fig.height = 6, dpi = 600, retina = 1)
Sys.setlocale("LC_TIME", "C")
```

# Setup

```{r packages}
library("tidyverse")
library("raster")
library("here")
library("sf")
```


# Data

```{r data}
### read all environmental raster data ----

files<-dir(here::here("data-raw",
                "geo-raw",
                "all_environmental_rasters_10m_3035"),pattern = "*.tif")

raster_stack <- files %>%
  map(~raster(file.path(here::here("data-raw",
                "geo-raw",
                "all_environmental_rasters_10m_3035"), .)))%>%
  stack()

names(raster_stack)


# create own function, focal analysis can't be applied on raster stack / brick simulatenously ----

multiFocal <- function(x, w=matrix(1, nr=11, nc=11), ...) {

   if(is.character(x)) {
     x <- brick(x)
   }
   # The function to be applied to each individual layer
   fun <- function(ind, x, w, ...){
     focal(x[[ind]], w=w, ...)
   }

   n <- seq(nlayers(x))
   list <- lapply(X=n, FUN=fun, x=x, w=w, ...)

   out <- stack(list)
   return(out)
}

################################################################################

# Apply focal mean on all raster layers ----

 
focal_mean_stack<-raster_stack%>%
  multiFocal(fun=mean)

names(focal_mean_stack)<-names(raster_stack)

plot(focal_mean_stack,colna="red")
```

```{r extract data}
ct_locations<-readRDS(here("output",
                           "data-proc",
                           "all_seasons",
                           "stacked_raster_values_and_garden_CT_all_seasons_no_nas_proc_20221117.RDS"))

ct_spatial<-st_as_sf(ct_locations,coords = c("Long","Lat"),remove=F,crs=32633) %>%
  st_transform(crs = 3035)

#### extract covariates ----

cov<-terra::extract(focal_mean_stack,ct_spatial)%>%
  data.frame()

#### bind

ct_cov<-cbind(ct_locations,cov)

saveRDS(ct_cov,here("output",
                    "data-proc",
                    "all_seasons",
                    "ct_focal_covariates_100.RDS"))


test<-ct_cov%>%dplyr::select(imperv_100,
                             imperviousness_berlin_copernicus_raster_10m_2018_3035)

View(test)

```

```{r correlation at ct locations}

cor<-cor(cov, use = "complete.obs")%>%
  data.frame()%>%
  as.matrix()


ggplot(data = melted_cor, aes(x=Var2, y=forcats::fct_rev(Var1), fill=value)) +
  geom_tile() +
  geom_text(aes(
    label = format(round(value, 2), nsmall = 2),
    color = abs(value) < .75
  )) +
  coord_fixed(expand = F) +
  scale_color_manual(values = c("white", "black"),
                     guide = "none") +
  scale_fill_distiller(
    palette = "RdBu", na.value = "white",
    direction = 1, limits = c(-1, 1)
  ) +
  labs(x = NULL, y = NULL) + scale_x_discrete(position = "top")+
  theme(panel.border = element_rect(color = NA, fill = NA),
        axis.text.x = element_text(angle = 45, hjust=0,size = 12),
        axis.text.y = element_text(size = 12),
        legend.key.size = unit(1.2,"cm"),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 20))


ggsave(here("plots","ct_correlation.png"),width = 12, height = 9)

```


```{r correlation of full raster, eval=FALSE, echo=TRUE}
cor<-as.data.frame(layerStats(raster_stack,stat="pearson",na.rm = T))
colnames(cor)<-rownames(cor)
cor<-as.matrix(cor[,1:10])
cor[cor>=1]=1;cor[upper.tri(cor)]<-NA

melted_cor<-reshape2::melt(cor)

ggplot(data = melted_cor, aes(x=Var2, y=Var1, fill=value)) +
  geom_tile() +
  geom_text(aes(
    label = format(round(value, 2), nsmall = 2),
    color = abs(value) < .75
  )) +
  coord_fixed(expand = FALSE) +
  scale_color_manual(values = c("white", "black"),
                     guide = "none") +
  scale_fill_distiller(
    palette = "RdBu", na.value = "white",
    direction = 1, limits = c(-1, 1)
  ) +
  labs(x = NULL, y = NULL) + scale_x_discrete(position = "top")+
  theme(panel.border = element_rect(color = NA, fill = NA),
        legend.position = c(.95, .4),
        axis.text.x = element_text(angle = 45, hjust=0,size = 15),
        axis.text.y = element_text(size = 15),
        legend.key.size = unit(1.2,"cm"),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 20))

#ggsave(here("plots","raster_correlation.png"),width = 12, height = 9)


```




***

<details><summary>Session Info</summary>

```{r sessionInfo}
## DO NOT REMOVE!
## We store the settings of your computer and the current versions of the
## packages used to allow for reproducibility
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>
