---
title: "02_Squirrel_community_temporal_analyses_preparation_temp"
author: "Sinah Drenske, Julie Louvrier, Aimara Planillo, Stephanie Kramer-Schadt"
date: "10 2 2022"
output: html_document
---

```{r setup, include=FALSE}
## You can ignore this chunk in most cases
## If you want to modify chunk options, you can do it here for all chunks or
## add the options in the repsective chunk header, e.g. `{r, message = FALSE}`
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE,
                      fig.width = 9, fig.height = 6, dpi = 500, 
                      retina = 1, fig.showtext = TRUE)
```

* **Research question:do urban mesocarnivores experience temporal partitioning in gardens? **
* **Study area: Berlin fall 2018, spring 2019, fall 2019, spring 2020, fall 2020**
* **Data: all seasons ** 


# Setup
## Packages

```{r packages}
## for non-CRAN packages please keep install instruction
## but commented so it is not run each time, e.g.
# devtools::install_github("EcoDynIZW/template")

## libraries used in this script
## please add ALL LIBRARIES NEEDED HERE
## please remove libraries from the list that are not needed anymore 
## at a later stage
#### load required libraries ####
package.list=c("camtrapR",
               #"camtrapRdeluxe",
               "dplyr",
               "evaluate",
               "gdata",
               "here",
               "janitor",
               "lubridate",
               "maptools",
               "optimbase",
               "plyr",
               "raster",
               "readxl",
               #"rgdal",
               #"rgeos",
               #"rjags",
               "rlecuyer",
               #"sf",
               "showtext",
               "snowfall",
               #"sp",
               "stringr",
               "tidyverse"
               )

for (package in package.list) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}

```


## Loading data

```{r data}
## Loading the environmental variables and using only the user IDs that are within the cov table
stacked_raster_values_and_garden_CT_all_seasons_no_nas <- readRDS(here::here("data-raw", "r-raw", "Louvrier_2021_JAE_UrbanMesocarnivores_Covariates_cameras_Dryad2021_10_29.RDS"))

## Camera Traps detection histories
CT_act_date_formated_delta30 <- readRDS( here::here("data-raw", "r-raw", "Louvrier_2021_JAE_UrbanMesocarnivores_Camera_detections_Dryad2021_11_05.RDS"))
```  

# Calculate the time intervals between last detections of the primary species (A) and first detection of the secondary species (B) 

```{r}
#taking out pictures between 6 pm and 5am 
CT_act_day <- CT_act_date_formated_delta30
CT_act_day$Time <- strptime(CT_act_day$Time, "%H:%M:%S") #ugh somehow it adds the date of today

#extract the hours after between 5am and 6pm, 
medium_day <- CT_act_day %>% dplyr::filter(Time >= paste0(gsub("-", "-", Sys.Date())," 05:00:00") 
                                & Time <= paste0(gsub("-", "-", Sys.Date())," 18:00:00"))

medium_day2 <- CT_act_day %>% dplyr::filter(Time >= paste0(gsub("-", "-", Sys.Date())," 05:00:00") 
                                & Time <= paste0(gsub("-", "-", Sys.Date())," 18:00:00"))


### Bekommt man das aktuelle Dtaum irgendwie weg????? Das muss doch gehen
















#saving the output
saveRDS(medium_day, file = here::here("output", "data-proc", "temporal_processed_data", paste0("medium_day",gsub("-", "_", Sys.Date()),".RDS")))

# !!!!! if you have issues with camtrapRdelux !!!!!

# install.packages("remotes")
# remotes::install_github("carlopacioni/camtrapRdeluxe")
# 
# unzip("~/Downloads/camtrapRdeluxe-master.zip")
# file.rename("camtrapRdeluxe-master", "camtrapRdeluxe")
# system("R CMD build camtrapRdeluxe")
# system('defaults write org.R-project.R force.LANG en_US.UTF-8') #LINE TO RUN IN CASE OF ERROR AGAIN

```



