---
date: "`r Sys.Date()`"
output: 
    distill::distill_article:
        highlight: kate      ## styling of code
        code_folding: false  ## if `true` you can expand and shrink code chunks
        toc: true            ## if `true` adds a table of content
        toc_depth: 2         ## level to be displayed in the table of content
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      dev = "ragg_png", fig.width = 9, fig.height = 6, dpi = 600, retina = 1)
Sys.setlocale("LC_TIME", "C")
```

# Setup

```{r packages}
library("tidyverse")
library("raster")
library("here")
library("sf")
```


# Data

```{r data}
### read all environmental raster data ----
imperviousness_2018<-
  raster(here("data-raw",
            "geo-raw",
            "imperviousness_berlin_copernicus_raster_10m_2018_3035",
            "imperviousness_berlin_copernicus_raster_10m_2018_3035.tif"
            ))%>%focal(w=matrix(1,nrow=11,ncol = 11),fun=mean)


crs(imperviousness_2018)<-crs("+init=epsg:3035")
plot(imperviousness_2018)

population_density_2019<-
  raster(here("data-raw",
              "geo-raw",
              #"population_density_ha_berlin_10m_2019_3035.tif"
              "population-density_berlin_2019_10m_03035_tif",
              "population-density_berlin_2019_10m_03035.tif"
            ))

# population_density_2019_2<-
#   raster(here("data-raw",
#               "geo-raw",
#               "population_density_ha_berlin_10m_2019_3035.tif"
#               #"population-density_berlin_2019_10m_03035_tif",
#               #"population-density_berlin_2019_10m_03035.tif"
#             ))

plot(population_density_2019)
```

```{r extract data}
ct_locations<-readRDS(here::here("output",
                           "data-proc",
                           "all_seasons",
                           "stacked_raster_values_and_garden_CT_all_seasons_no_nas_proc_20230105.RDS"))
                           #"stacked_raster_values_and_garden_CT_all_seasons_no_nas_proc_20221117.RDS"))

ct_spatial<-st_as_sf(ct_locations,coords = c("Long","Lat"),remove=F,crs=32633)%>%
  st_transform(crs = 3035)


#### extract covariates ----

cov_imperviousness_2018<-raster::extract(x=imperviousness_2018,y=ct_spatial)%>%
  data.frame()

colnames(cov_imperviousness_2018)<-"imperviousness_2018"

# population density

cov_population_density_2019<-terra::extract(x=population_density_2019,y=ct_spatial)%>%
  data.frame()

colnames(cov_population_density_2019)<-"population_density_2019"

# Pop 2
cov_population_density_2019_2<-terra::extract(x=population_density_2019_2,y=ct_spatial)%>%
  data.frame()

colnames(cov_population_density_2019_2)<-"population_density_2019"


# distance to border

berlin <- st_read(here("data-raw",
                       "geo-raw",
                       "berlin_city_border_25833.gpkg"), crs = 25833)%>% 
  st_union() %>% 
  st_transform(crs = 3035) %>% 
  st_cast(to = 'LINESTRING')

# berlin_districts <- st_read(here("data-raw",
#                                  "geo-raw",
#                                  "districs_berlin_2022_poly_03035_gpkg",
#                                  "districs_berlin_2022_poly_03035.gpkg"), crs = 3035) %>% 
#   st_union(by_feature = FALSE) %>% 
#   #st_transform(crs = 3035) %>% 
#   st_cast(to = 'MULTILINESTRING') %>%
#   st_cast(to = 'LINESTRING')

#plot(berlin)
#plot(berlin_districts)

dist_border <- st_distance(ct_spatial, berlin)

colnames(dist_border)<-"distance_to_border"


# bind data
ct_cov <- cbind(ct_spatial,
              cov_imperviousness_2018,
              cov_population_density_2019, cov_population_density_2019_2,
              dist_border)#%>%
  #dplyr::select(-c(10,12,13,15:18)) # only to compare them
  #dplyr::select(-c(pop_100,distance_border,imperv_100))


# population density 

# saveRDS(ct_cov,here::here("output",
#                     "data-proc",
#                     "all_seasons",
#                     "ct_focal_covariates_100_20230118.RDS"))
#                     #"ct_focal_covariates_100.RDS"))
```

# Plots
## Population density
```{r}
ggplot(data = ct_cov, mapping = aes(x = Station, y = population_density_2019.1)) + 
  geom_point() + 
  ylim(0, 700) + 
  xlim(0, 700) + 
  labs(title = "Population density")

ggplot(data = ct_cov, mapping = aes(x = Station, y = population_density_2019)) + 
  geom_point() + 
  ylim(0, 700) + 
  xlim(0, 700) + 
  labs(title = "Population density by Marius")

ggplot(data = ct_cov, mapping = aes(x = population_density_2019.1, y = population_density_2019)) + 
  geom_point() + 
  ylim(0, 700) + 
  xlim(0, 700) + 
  labs(title = "Comparison of population density values")
```

```{r}
table(is.na(ct_cov$pop_100), useNA = "always")
table(is.na(ct_cov$population_density_2019), useNA = "always") #113 NaN
#table(ct_cov$population_density_2019, useNA = "always")
```


## Imperviousness
```{r}
ggplot(data = ct_cov, mapping = aes(x = Station, y = imperv_100)) + 
  geom_point() + 
  labs(title = "Imperviousness")
ggplot(data = ct_cov, mapping = aes(x = Station, y = imperviousness_2018)) + 
  geom_point() + 
  labs(title = "Imperviousness by Marius")
ggplot(data = ct_cov, mapping = aes(x = imperv_100, y = imperviousness_2018)) + 
  geom_point() + 
  labs(title = "comparison of imperviousness values")
```

## Distance to border
```{r}
ggplot(data = ct_cov, mapping = aes(x = Station, y = distance_border)) + 
  geom_point() + 
  ylim(0, 20000) + 
  labs(title = "Distance to border")

ggplot(data = ct_cov, mapping = aes(x = Station, y = as.numeric(distance_to_border))) + 
  geom_point()+ 
  ylim(0, 20000) + 
  labs(title = "Distance to border by Marius")

ggplot(data = ct_cov, mapping = aes(x = distance_border, y = as.numeric(distance_to_border))) + 
  geom_point()+ 
  ylim(0, 15000) + 
  xlim(0, 15000) +
  labs(title = "Comparison of disance to border values")
```

```{r correlation at ct locations}

cov<-ct_cov%>%
  dplyr::select(garden_size,
                Local_tree_cover,
                fence_height,
                dist_water_100,
                noise_100,
                tree_cover_100,
                dogs_binary,
                cats_binary,
                trees_of_interest,
                imperviousness_2018,
                population_density_2019,
                distance_to_border                
                )%>%
  mutate(distance_to_border=as.numeric(distance_to_border))%>%
  st_drop_geometry()



cor_loc<-cor(cov, use = "complete.obs")%>%
  data.frame()%>%
  as.matrix()

melted_cor_loc<-reshape2::melt(cor_loc)

ggplot(data = melted_cor_loc, aes(x=Var2, y=forcats::fct_rev(Var1), fill=value)) +
  geom_tile() +
  geom_text(aes(
    label = format(round(value, 2), nsmall = 2),
    color = abs(value) < .75
  )) +
  coord_fixed(expand = F) +
  scale_color_manual(values = c("white", "black"),
                     guide = "none") +
  scale_fill_distiller(
    palette = "RdBu", na.value = "white",
    direction = 1, limits = c(-1, 1)
  ) +
  labs(x = NULL, y = NULL) + scale_x_discrete(position = "top")+
  theme(panel.border = element_rect(color = NA, fill = NA),
        axis.text.x = element_text(angle = 45, hjust=0,size = 12),
        axis.text.y = element_text(size = 12),
        legend.key.size = unit(1.2,"cm"),
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 20))


ggsave(here("plots","ct_correlation.png"),width = 12, height = 9)

```


```{r correlation of full raster, eval=FALSE, echo=TRUE}
# cor<-as.data.frame(layerStats(raster_stack,stat="pearson",na.rm = T))
# colnames(cor)<-rownames(cor)
# cor<-as.matrix(cor[,1:10])
# cor[cor>=1]=1;cor[upper.tri(cor)]<-NA
# 
# melted_cor<-reshape2::melt(cor)
# 
# ggplot(data = melted_cor, aes(x=Var2, y=Var1, fill=value)) +
#   geom_tile() +
#   geom_text(aes(
#     label = format(round(value, 2), nsmall = 2),
#     color = abs(value) < .75
#   )) +
#   coord_fixed(expand = FALSE) +
#   scale_color_manual(values = c("white", "black"),
#                      guide = "none") +
#   scale_fill_distiller(
#     palette = "RdBu", na.value = "white",
#     direction = 1, limits = c(-1, 1)
#   ) +
#   labs(x = NULL, y = NULL) + scale_x_discrete(position = "top")+
#   theme(panel.border = element_rect(color = NA, fill = NA),
#         legend.position = c(.95, .4),
#         axis.text.x = element_text(angle = 45, hjust=0,size = 15),
#         axis.text.y = element_text(size = 15),
#         legend.key.size = unit(1.2,"cm"),
#         legend.text = element_text(size = 15),
#         legend.title = element_text(size = 20))
# 
# ggsave(here("plots","raster_correlation.png"),width = 12, height = 9)


```




***

<details><summary>Session Info</summary>

```{r sessionInfo}
## DO NOT REMOVE!
## We store the settings of your computer and the current versions of the
## packages used to allow for reproducibility
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>
