---
title: "Squirrel activity: Data Preparation" ## name of your project and analysis step
description: |
    The aim of this study is...
author:
    ## author information; single arguemnts can be deleted if not needed
    - name: "John Smith"
      url: https://izw-berlin.de/en/john-smith-en.html  
      affiliation: Leibniz Institute for Zoo and Wildlife Research
      affiliation_url: https://izw-berlin.de/en/
      orcid_id: 0000-0000-0000-0000
    - name: "Jane Doe"
      url: https://janedoe.com
      affiliation: Leibniz Institute for Zoo and Wildlife Research
      affiliation_url: https://izw-berlin.de/en/
    ## add more authors with the same intendation and styling if needed 
    ## a new author always starts with a hyphen!
date: "`r Sys.Date()`"
output: 
    distill::distill_article:
        highlight: kate      ## styling of code
        code_folding: true  ## if `true` you can expand and shrink code chunks
        toc: true            ## if `true` adds a table of content
        toc_depth: 4         ## level to be displayed in the table of content
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      dev = "ragg_png", fig.width = 9, fig.height = 6, dpi = 600, retina = 1)
Sys.setlocale("LC_TIME", "C")
```

* **Research question:**
* **Study area:**
* **Data:** 


# Setup

```{r packages}
# install the package librarian, it loads and installs (if necessary) the specified packages from CRAN, GitHub or Bioconductor

#devtools::install_github("DesiQuintans/librarian")
librarian::shelf(update_all = FALSE,
                 #colorspace, 
                 #corrplot,
                 EcoDynIZW / d6berlin,
                 #extrafont, 
                 #gdata, 
                 #ggdist, 
                 #ggpubr, 
                 here, 
                 skimr, 
                 tidyverse
                 )
```


# Data

```{r data}
#loading the environmental variables and using only the user IDs that are within the cov table
env_var <- readRDS(here::here("output", 
                              "data-proc", 
                              "all_seasons",
                              "ct_focal_covariates_100_20230223.RDS"))
                              #"stacked_raster_values_and_garden_CT_all_seasons_no_nas_proc_20230124.RDS"))

#already formatted and filtered data 
# CT_act_date_proc <- readRDS(here::here("output", "data-proc", "all_seasons",
#                                        "CT_act_date_proc_20230124.RDS"))
CT_species_interest <- readRDS(here::here("output", 
                                          "data-proc", 
                                          "all_seasons",
                                          "CT_species_interest_time_20230223.RDS"))
```


Count the number of pictures per species per station 
```{r}
# build a vector for station IDs
station_IDs <- env_var$Station

# Build a table with the number of pictures per species of interest per station
# the full table should have 666 Stations * 5 species = 3330 rows

CT_per_station <- CT_species_interest[, c(1:11)] %>%
  droplevels() %>%
  dplyr::count(Species, Station)  %>% 
  group_by(Species, Station) %>%
  dplyr::summarise(sum_pic = sum(n)) %>%
  ungroup() %>% 
  complete(Station, Species, fill = list(sum_pic = 0)) %>%
  full_join(y = env_var[, c(1:20)], by = "Station") %>%
  replace_na(list(Species = "Squirrel", sum_pic = 0)) %>%
  droplevels()

# Squirrels per station
CT_squirrels_station <- CT_per_station %>%
  filter(Species == "Squirrel")

# Calculate a binary column (presence absence) per predator
CT_squirrels_station <- CT_per_station %>%
  filter(Species == "Squirrel") %>% 
  mutate(
    squirrels_cam_binary = case_when(
      Species == "Squirrel" & sum_pic > 0 ~ 1, 
      Species == "Squirrel" & sum_pic == 0 ~ 0)) %>%
  select(Station, squirrels_cam_binary) %>%
  right_join(y = CT_squirrels_station, by = "Station")

CT_squirrels_station <- CT_per_station %>%
  filter(Species == "Cat") %>% 
  mutate(
    cats_cam_binary = case_when(
      Species == "Cat" & sum_pic > 0 ~ 1, 
      Species == "Cat" & sum_pic == 0 ~ 0)) %>%
  select(Station, cats_cam_binary) %>%
  right_join(y = CT_squirrels_station, by = "Station")

CT_squirrels_station <- CT_per_station %>%
  filter(Species == "Marten") %>% 
  mutate(
    marten_cam_binary = case_when(
      Species == "Marten" & sum_pic > 0 ~ 1, 
      Species == "Marten" & sum_pic == 0 ~ 0)) %>%
  select(Station,  marten_cam_binary) %>%
  full_join(y = CT_squirrels_station, by = "Station")

# CT_squirrels_station <- CT_per_station %>%
#   filter(Species == "Raccoon") %>% 
#   mutate(
#     raccoon_cam_binary = case_when(
#       Species == "Raccoon" & sum_pic > 0 ~ 1, 
#       Species == "Raccoon" & sum_pic == 0 ~ 0)) %>%
#   select(Station,  raccoon_cam_binary) %>%
#   full_join(y = CT_squirrels_station, by = "Station")
# 
# CT_squirrels_station <- CT_per_station %>%
#   filter(Species == "Red Fox") %>% 
#   mutate(
#     fox_cam_binary = case_when(
#       Species == "Red Fox" & sum_pic > 0 ~ 1, 
#       Species == "Red Fox" & sum_pic == 0 ~ 0)) %>%
#   select(Station,  fox_cam_binary) %>%
#   full_join(y = CT_squirrels_station, by = "Station")
```



Compare cats_binary (cats as pets) and cats_cam_binary
```{r}
table(CT_squirrels_station$cats_binary)
table(CT_squirrels_station$cats_cam_binary) # many more cats on cameras than per garden as pets
```

Change the column type
```{r}
CT_squirrels_station <- 
  CT_squirrels_station %>%
  dplyr::mutate(across(.cols = c(squirrels_cam_binary, cats_cam_binary, marten_cam_binary), # , raccoon_cam_binary, fox_cam_binary
                       .fns =  as.factor))%>%
  droplevels()
```

Combine the binary columns with the data per station
```{r}
env_var <- env_var %>%
  left_join(y = CT_squirrels_station[, c(1:4)], by = "Station") %>%
  droplevels()
```

Build a combined table of CT data and environmental data

```{r}
CT_species_interest <- CT_species_interest %>%
  left_join(y = env_var[, c(1, 5:23)], by = "Station") %>%
  droplevels()
```

Build a table only for squirrels
```{r}
CT_squirrels <- CT_species_interest %>%
  filter(Species == "Squirrel") %>%
  droplevels()
```

## Save these data sets
```{r}
# # Environmental data wit squirrel and predator presence
# saveRDS(object = env_var,
#         file = here::here("output",
#                           "data-proc",
#                           "all_seasons",
#                           "env_var_binary_species_20230223.RDS"))
# 
# # CT species interest with env data
# saveRDS(object = CT_species_interest,
#         file = here::here("output",
#                           "data-proc",
#                           "all_seasons",
#                           "CT_species_interest_with_env_20230223.RDS"))
# 
# # CT Squirrels
# saveRDS(object = CT_squirrels,
#         file = here::here("output",
#                           "data-proc",
#                           "all_seasons",
#                           "CT_squirrels_20230223.RDS"))
# 
# # CT species of interest per station
# saveRDS(object = CT_per_station,
#         file = here::here("output",
#                           "data-proc",
#                           "all_seasons",
#                           "CT_species_interest_per_station_20230223.RDS"))
# 
# # CT squirrels per station
# saveRDS(object = CT_squirrels_station,
#         file = here::here("output",
#                           "data-proc",
#                           "all_seasons",
#                           "CT_squirrels_per_station_20230223.RDS"))
```


***

<details><summary>Session Info</summary>

```{r sessionInfo}
## DO NOT REMOVE!
## We store the settings of your computer and the current versions of the
## packages used to allow for reproducibility
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>
