---
title: "Squirrel activity: General description - models" ## name of your project and analysis step
description: |
    The aim of this study is...
author:
    ## author information; single arguemnts can be deleted if not needed
    - name: "John Smith"
      url: https://izw-berlin.de/en/john-smith-en.html  
      affiliation: Leibniz Institute for Zoo and Wildlife Research
      affiliation_url: https://izw-berlin.de/en/
      orcid_id: 0000-0000-0000-0000
    - name: "Jane Doe"
      url: https://janedoe.com
      affiliation: Leibniz Institute for Zoo and Wildlife Research
      affiliation_url: https://izw-berlin.de/en/
    ## add more authors with the same intendation and styling if needed 
    ## a new author always starts with a hyphen!
date: "`r Sys.Date()`"
output: 
    distill::distill_article:
        highlight: kate      ## styling of code
        code_folding: false  ## if `true` you can expand and shrink code chunks
        toc: true            ## if `true` adds a table of content
        toc_depth: 2         ## level to be displayed in the table of content
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      dev = "ragg_png", fig.width = 9, fig.height = 6, dpi = 600, retina = 1)
Sys.setlocale("LC_TIME", "C")
```

* **Research question:**
* **Study area:**
* **Data:** 


# Setup

```{r packages}
# install the package librarian, it loads and installs (if necessary) the specified packages from CRAN, GitHub or Bioconductor

#devtools::install_github("DesiQuintans/librarian")
librarian::shelf(#camtrapR,
                 #dplyr,
                 #evaluate,
                 bayestestR, 
                 easystats / easystats, 
                 effects,
                 ggeffects,
                 #gdata, 
                 #ggplot2, 
                 ggpubr, 
                 here, 
                 insight,
                 performance, 
                 #janitor, 
                 #lubridate, 
                 #maptools, 
                 #ropenscilabs / ochRe,
                 # "optimbase", maybe needed but has to be installed from the CRAN archive https://cran.r-project.org/web/packages/optimbase/index.html
                 plyr,
                 rstanarm, 
                 #raster,
                 #readxl, 
                 #rgdal, 
                 #rgeos, 
                 #rjags, 
                 #rlecuyer, 
                 #thomasp85 / scico, 
                 #sf, 
                 #showtext, 
                 #skimr, 
                 #snowfall, 
                 #sp, 
                 stringr, 
                 tidyverse, 
                 #vroom
                 )
```


# Data

```{r data}
# camera trap detection historie of squirrels combined with the environmental data
CT_squirrels_station <- readRDS(here::here("output", "data-proc", "all_seasons", "CT_squirrels_station_with_garden_var_20230106.RDS"))
```

# Preparation
```{r}
# Factorize some columns
CT_squirrels_station <- CT_squirrels_station %>% dplyr::mutate(across(.cols = c(Season, project_phase, garden_type, lockdown,  
                                                                         dogs_binary, cats_binary, trees_of_interest), 
                                                               .fns =  as.factor))
```


# GLM
## Without time limit - baseR
### Full model
```{r}
# Null model
full_null_mod <- glm(formula = n_pics ~ 1, 
                     family = "poisson", 
                     data = CT_squirrels_station)
summary(full_null_mod)
with(summary(full_null_mod), 1 - deviance/null.deviance)

# Null model with Season and lockdown
full_null_mod_s_l <- glm(formula = n_pics ~ 1 + Season + lockdown,
                         family = "poisson", 
                         data = CT_squirrels_station)
summary(full_null_mod_s_l)
with(summary(full_null_mod_s_l), 1 - deviance/null.deviance)

# Full model with explanatory variables of urban and garden level
full_mod <- glm(formula = n_pics ~ scale(imperviousness_berlin_copernicus_raster_10m_2018_3035) + scale(tree_cover_100) + 
                          scale(distance_to_border_3035) + scale(human_population_density_raster_10m_2017_3035) + scale(noise_100) + 
                          garden_type + scale(garden_size) + dogs_binary + cats_binary + trees_of_interest + Season + lockdown,
                family = "poisson",
                data = CT_squirrels_station)
summary(full_mod)
with(summary(full_mod), 1 - deviance/null.deviance)
```

```{r}
plot(allEffects(full_mod), type = 'response')
plot(allEffects(full_mod), type = 'response', ylim = c(0,40))
```

### Urban model
```{r}
urban_mod <- glm(formula = n_pics ~ scale(imperviousness_berlin_copernicus_raster_10m_2018_3035) + scale(tree_cover_100) + 
                          scale(distance_to_border_3035) + scale(human_population_density_raster_10m_2017_3035) + scale(noise_100) + 
                          Season + lockdown,
                 family = "poisson",
                 data = CT_squirrels_station)
summary(urban_mod)
with(summary(urban_mod), 1 - deviance/null.deviance)
```


```{r}
plot(allEffects(urban_mod), type = 'response')
plot(allEffects(urban_mod), type = 'response', ylim = c(0,40))
```

### Garden model
```{r}
garden_mod <- glm(formula = n_pics ~ garden_type + scale(garden_size) + dogs_binary + cats_binary + trees_of_interest + Season + lockdown,
                  family = "poisson", 
                  data = CT_squirrels_station)
summary(garden_mod)
with(summary(garden_mod), 1 - deviance/null.deviance)
```


```{r}
plot(allEffects(garden_mod), type = 'response')
plot(allEffects(garden_mod), type = 'response', ylim = c(0,40))
```

### Comparison of all models
```{r}
summary(full_mod)
summary(urban_mod)
summary(garden_mod)
```

```{r}
plot(allEffects(full_mod), type = 'response', ylim = c(0,40))
plot(allEffects(urban_mod), type = 'response', ylim = c(0,40))
plot(allEffects(garden_mod), type = 'response', ylim = c(0,40))
```
## Without time limit - bayestestR
### Full model
```{r}
# Null model
full_null_mod <- stan_glm(formula = n_pics ~ 1, 
                          family = "poisson", 
                          data = CT_squirrels_station)

# Null model with Season and lockdown
full_null_mod_s_l <- stan_glm(formula = n_pics ~ 1 + Season + lockdown, 
                              family = "poisson", 
                              data = CT_squirrels_station)

# Full model with explanatory variables of urban and garden level
full_mod <- stan_glm(formula = n_pics ~ scale(imperviousness_berlin_copernicus_raster_10m_2018_3035) + scale(tree_cover_100) + 
                          scale(distance_to_border_3035) + scale(human_population_density_raster_10m_2017_3035) + scale(noise_100) + 
                          garden_type + scale(garden_size) + dogs_binary + cats_binary + trees_of_interest + Season + lockdown,
                     family = "poisson", 
                     data = CT_squirrels_station)

full_mod2 <- stan_glmer(formula = n_pics ~ (1|Station) + scale(imperviousness_berlin_copernicus_raster_10m_2018_3035) + scale(tree_cover_100) + 
                          scale(distance_to_border_3035) + scale(human_population_density_raster_10m_2017_3035) + scale(noise_100) + 
                          garden_type + scale(garden_size) + dogs_binary + cats_binary + trees_of_interest + Season + lockdown,
                     family = "poisson", 
                     data = CT_squirrels_station)
```


```{r}
# Summaries
describe_posterior(full_null_mod, test = c("p_direction", "rope", "bayesfactor"))
describe_posterior(full_null_mod_s_l, test = c("p_direction", "rope", "bayesfactor"))
describe_posterior(full_mod, test = c("p_direction", "rope", "bayesfactor"))
describe_posterior(full_mod2, test = c("p_direction", "rope", "bayesfactor"))
```


```{r}
posteriors <- get_parameters(full_mod)

# Example plots
ggplot(posteriors, aes(x = 'scale(distance_to_border_3035)')) +
  geom_density(fill = "red")

ggplot(posteriors, aes(x = dogs_binary1)) +
  geom_density(fill = "red")
```

```{r}
# Plot of the significance
plot(rope(full_mod))
plot(rope(full_mod2))
```
```{r}
model_performance(full_mod)
# explanantions of the abbreviations: https://easystats.github.io/performance/reference/model_performance.stanreg.html
# ELPD = expected log predictive density
# LOOIC = leave one out cross validation information criterion
# WAIC = widely applicable information criterion
# RMSE = root mean squared error
# Sigma = residual standard deviation
# Score_Log = score of logarithmic proper scoring rule
# Score_spherical = score of spherical proper scoring rule
```


### Urban model
```{r}
# Full model with explanatory variables of urban and garden level
urban_mod <- stan_glm(formula = n_pics ~ scale(imperviousness_berlin_copernicus_raster_10m_2018_3035) + scale(tree_cover_100) + 
                          scale(distance_to_border_3035) + scale(human_population_density_raster_10m_2017_3035) + scale(noise_100) + 
                          Season + lockdown,
                     family = "poisson", 
                     data = CT_squirrels_station)
```


```{r}
describe_posterior(urban_mod, test = c("p_direction", "rope", "bayesfactor"))
```


```{r}
posteriors_urban <- get_parameters(urban_mod)

# Example plots
ggplot(posteriors_urban, aes(x = 'scale(distance_to_border_3035)')) +
  geom_density(fill = "red")
```


```{r}
# Plot of the significance
plot(rope(urban_mod))
```


```{r}
model_performance(urban_mod)
# explanantions of the abbreviations: https://easystats.github.io/performance/reference/model_performance.stanreg.html
# ELPD = expected log predictive density
# LOOIC = leave one out cross validation information criterion
# WAIC = widely applicable information criterion
# RMSE = root mean squared error
# Sigma = residual standard deviation
# Score_Log = score of logarithmic proper scoring rule
# Score_spherical = score of spherical proper scoring rule
```


### Garden model
```{r}
# Full model with explanatory variables of urban and garden level
garden_mod <- stan_glm(formula = n_pics ~ garden_type + scale(garden_size) + dogs_binary + cats_binary + trees_of_interest + Season + lockdown,
                     family = "poisson", 
                     data = CT_squirrels_station)
```


```{r}
describe_posterior(garden_mod, test = c("p_direction", "rope", "bayesfactor"))
```


```{r}
posteriors_garden <- get_parameters(garden_mod)

ggplot(posteriors_garden, aes(x = dogs_binary1)) +
  geom_density(fill = "red")
```


```{r}
# Plot of the significance
plot(rope(garden_mod))
```


```{r}
model_performance(garden_mod)
# explanantions of the abbreviations: https://easystats.github.io/performance/reference/model_performance.stanreg.html
# ELPD = expected log predictive density
# LOOIC = leave one out cross validation information criterion
# WAIC = widely applicable information criterion
# RMSE = root mean squared error
# Sigma = residual standard deviation
# Score_Log = score of logarithmic proper scoring rule
# Score_spherical = score of spherical proper scoring rule
```

### Comparison of all models
```{r}
compare_parameters(full_mod, urban_mod, garden_mod)
```


```{r}
#compare_performance(full_null_mod, full_null_mod_s_l, full_mod)
compare_performance(full_null_mod, full_null_mod_s_l, full_mod, urban_mod, garden_mod)
```



***

<details><summary>Session Info</summary>

```{r sessionInfo}
## DO NOT REMOVE!
## We store the settings of your computer and the current versions of the
## packages used to allow for reproducibility
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>
