---
title: "Quick_test"
author: "Sinah Drenske"
date: "19 10 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup
## Packages
```{r packages, message=FALSE, warning=FALSE}
## for non-CRAN packages please keep install instruction
## but commented so it is not run each time, e.g.
# devtools::install_github("EcoDynIZW/template")

## libraries used in this script
## please add ALL LIBRARIES NEEDED HERE
## please remove libraries from the list that are not needed anymore 
## at a later stage
package.list=c("camtrapR",
               "dplyr",
               "evaluate",
               "ggplot2",
               "gdata",
               "ggpubr",
               "here",
               "janitor",
               "lubridate",
               "maptools",
               # "optimbase", maybe needed but has to be installed from the CRAN archive https://cran.r-project.org/web/packages/optimbase/index.html
               "plyr",
               "raster",
               "readxl",
               #"rgdal",
               #"rgeos",
               #"rjags",
               "rlecuyer",
               #"sf",
               "showtext",
               "skimr",
               "snowfall",
               #"sp",
               "stringr",
               "tidyverse",
               "vroom"
               )

for (package in package.list) {
  if (!require(package, character.only=T, quietly=T)) {
    install.packages(package)
    library(package, character.only=T)
  }
}

```




## Data
```{r}
# julie_data <- readRDS(here::here("data-raw", "r-raw", "Old", "Louvrier_2021_JAE_UrbanMesocarnivores_Covariates_cameras_Dryad2021_10_29.RDS"))
# 
# julie_data2 <- readRDS(here::here("data-raw", "r-raw", "Old", "Louvrier_2021_JAE_UrbanMesocarnivores_Camera_detections_Dryad2021_11_05.RDS"))
```

```{r}
# ct_test <- unique(CT_act_date_formated[ ,2:3 ])
# table(ct_test$Season)
# table(stacked_raster_values_and_garden_CT_all_seasons_no_nas$project_phase)
# table(env_var2$project_phase)
```

# Problem season and station
```{r}
# CT_unique <- CT_act_date_formated[!duplicated(CT_act_date_formated$Station), ]
# stacked_raster_values_and_garden_CT_all_seasons_no_nas %>% 
#   left_join(y = CT_unique)
```

```{r}
# CT_stations_phase <- CT_act_date_formated %>%
#   group_by(Station) %>%
#   summarise(count = n_distinct(project_phase))
```


```{r}
# options(max.print = 10000)
# table(CT_act_date_formated$Station, CT_act_date_formated$project_phase)
```


```{r}
# CT_1553 <- CT_act_date_formated[CT_act_date_formated$Station == 1553, ]
# CT_1769 <- CT_act_date_formated[CT_act_date_formated$Station == 1769, ]
# CT_1869 <- CT_act_date_formated[CT_act_date_formated$Station == 1869, ]
```


# Exploratory data analysis
```{r}
# library("DataExplorer")
# library("tidyverse")
```


```{r}
# gss_cat
# 
# gss_cat %>% glimpse()
```

```{r}
# gss_cat %>% 
#   create_report(output_file = "gss_cat_data_profile_report", 
#                 output_dir = "", 
#                 y = "rincome", 
#                 report_title = "EDA Report - GSS data")
```


```{r}
# garden_variables %>% 
#   create_report(output_file = "garden_variables_data_report", 
#                 #output_dir = "", 
#                 #y = "rincome", 
#                 report_title = "EDA report of the garden variables")
```

# Import fonts
```{r}
# # Loading fonts (with package extrafont)
# library(extrafont)
# #font_import()
# loadfonts(device = "win")
# fonts()

```


```{r}
# windowsFonts()
# wf <- windowsFonts()
# names(wf[wf=="Roboto"])
```

```{r}
# ggplot(mtcars, aes(factor(cyl), fill = factor(vs))) +
#   geom_bar(position = "dodge")
# 
# ggplot(mtcars, aes(factor(cyl), fill = factor(vs))) +
#   geom_bar(position = "dodge2")
# 
# ggplot(mtcars, aes(factor(cyl), fill = factor(vs))) +
#   geom_bar(position = position_dodge(width = 0.9, preserve = "single"))
```

# Overlap plots + calculation
```{r}
# dat$time <- (hour(dat$DateTime)*60 + minute(dat$DateTime))/(24*60)  #time of day as fraction
# dat$radtime <- dat$time * 2 * pi

CT_squirrels$time_frac <- (hour(CT_squirrels$DateTimeOriginal)*60 + minute(CT_squirrels$DateTimeOriginal))/(24*60)
CT_squirrels$time_frac
CT_squirrels$radtime <- CT_squirrels$time_frac * 2 * pi
CT_squirrels$radtime

CT_squirrels <- sf::st_drop_geometry(CT_squirrels)
CT_squirrels_dogs <- CT_squirrels[CT_squirrels$dogs_binary == 1, ]$radtime
CT_squirrels_no_dogs <- CT_squirrels[CT_squirrels$dogs_binary == 0, ]$radtime
```

```{r}
overlapEst(A = CT_squirrels_dogs, B = CT_squirrels_no_dogs, kmax = 3, type = "all")
#overlap::overlapEst

```


# Mean activity time
```{r}
mean_squirrel_time2 <- CT_squirrels$Time %>%
  hms() %>%
  period_to_seconds() %>%
  mean() %>%
  seconds_to_period()

mean_squirrel_time
mean_squirrel_time2

typeof(CT_squirrels$Time)
class(CT_squirrels$Time)
```


# Time diff between pics
```{r}
CT_test <- CT_species_interest

id_CT <- unique(CT_test$Station)
species_CT <- unique(CT_test$Species)

CT_test$time_diff <- NA
```

```{r}
CT_squirrel2 <- CT_species_interest %>%
  filter(Species == "Squirrel")

id_CT <- unique(CT_squirrel2$Station)

CT_squirrel2$time_diff <- NA

# for (id in species_CT) {
# CT_ID <- CT_Test %>% 
#   filter(Species == species_CT[id])  
# CT_ID


for (pic in 1:(nrow(CT_squirrel2)-1)) {
 # for (i in id_CT) {
    if (CT_squirrel2$Station[pic+1] == CT_squirrel2$Station[pic]) {
      CT_squirrel2$time_diff[pic+1] <- difftime(time1 = CT_squirrel2$DateTimeOriginal[pic+1], time2 = CT_squirrel2$DateTimeOriginal[pic], units = "mins") 
    }
}
#}
```


## new approach
```{r}
CT_squirrel <- CT_species_interest %>%
  filter(Species == "Squirrel")

id_CT <- unique(CT_squirrel$Station)

CT_squirrel <- CT_squirrel %>%
  dplyr::group_by(project_phase, Station) %>%
  dplyr::arrange(DateTimeOriginal) %>% 
  mutate(diff_squirrels = as.numeric(difftime(time1 = DateTimeOriginal, time2 = dplyr::lag(DateTimeOriginal), units = "mins"))) %>%
  ungroup() %>%
  mutate(diff_squirrels = case_when(
    is.na(diff_squirrels) ~ 999, 
    TRUE ~ diff_squirrels)) %>% 
  group_by(project_phase, Station, Date) %>%
  filter(diff_squirrels > 1) %>%
  ungroup()
```


```{r}
CT_time_diff <- CT_species_interest %>%
  dplyr::group_by(Species, project_phase, Station) %>%
  dplyr::arrange(DateTimeOriginal) %>% 
  mutate(diff_squirrels = as.numeric(difftime(time1 = DateTimeOriginal, time2 = dplyr::lag(DateTimeOriginal), units = "mins"))) %>%
  ungroup() %>%
  mutate(diff_squirrels = case_when(
    is.na(diff_squirrels) ~ 999, 
    TRUE ~ diff_squirrels)) %>% 
  group_by(project_phase, Station, Date) %>%
  filter(diff_squirrels > 1) %>%
  ungroup()
```


```{r}
CT_time_diff2 <- CT_time_diff %>%
  dplyr::group_by(Species, project_phase, Station) %>%
  dplyr::arrange(DateTimeOriginal) %>% 
  mutate(diff_squirrels2 = as.numeric(difftime(time1 = DateTimeOriginal, time2 = dplyr::lag(DateTimeOriginal), units = "mins"))) %>%
  ungroup() %>%
  mutate(diff_squirrels2 = case_when(
    is.na(diff_squirrels2) ~ 999, 
    TRUE ~ diff_squirrels2)) %>% 
  group_by(project_phase, Station, Date) %>%
  filter(diff_squirrels2 > 1) %>%
  ungroup()
```

```{r}
CT_time_diff3 <- CT_species_interest %>%
  dplyr::group_by(Species, project_phase, Station) %>%
  dplyr::arrange(DateTimeOriginal) %>% 
  mutate(diff_samespecies = as.numeric(difftime(time1 = DateTimeOriginal, 
                                                time2 = dplyr::lag(DateTimeOriginal), 
                                                units = "mins"))) %>%
  ungroup() %>%
  mutate(diff_samespecies = case_when(
    is.na(diff_samespecies) ~ 999, 
    TRUE ~ diff_samespecies)) %>% 
  group_by(project_phase, Station, Date) %>%
  filter(diff_samespecies > 1) %>%
  ungroup() %>%
  dplyr::group_by(Species, project_phase, Station) %>%
  dplyr::arrange(DateTimeOriginal) %>% 
  mutate(diff_samespecies = as.numeric(difftime(time1 = DateTimeOriginal, 
                                                time2 = dplyr::lag(DateTimeOriginal), 
                                                units = "mins"))) %>%
  ungroup() %>%
  mutate(diff_samespecies = case_when(
    is.na(diff_samespecies) ~ 999, 
    TRUE ~ diff_samespecies)) %>% 
  group_by(project_phase, Station, Date) %>%
  filter(diff_samespecies > 1) %>%
  ungroup()
```

```{r}
range(CT_time_diff$diff_squirrels)
range(CT_time_diff2$diff_squirrels2)
range(CT_time_diff3$diff_samespecies)
```



```{r}
# CT_time_diff2 <- CT_species_interest %>%
#   dplyr::group_by(Species, project_phase, Station) %>%
#   dplyr::arrange(DateTimeOriginal) %>% 
#   mutate(diff_squirrels = as.numeric(difftime(time1 = DateTimeOriginal, time2 = dplyr::lag(DateTimeOriginal), units = "mins"))) %>%
#   ungroup() #%>%
  # mutate(diff_squirrels = case_when(
  #   is.na(diff_squirrels) ~ 999, 
  #   TRUE ~ diff_squirrels)) %>% 
  # group_by(project_phase, Station, Date) %>%
  # filter(diff_squirrels > 1) %>%
  # ungroup()
```



## Old
```{r}
CT_squirrel$time_diff <- NA


for (pic in 1:(nrow(CT_squirrel)-1)) {
 # for (i in id_CT) {
    if (CT_squirrel$Station[pic+1] == CT_squirrel$Station[pic]) {
      CT_squirrel$time_diff[pic+1] <- difftime(time1 = CT_squirrel$DateTimeOriginal[pic+1], time2 = CT_squirrel$DateTimeOriginal[pic], units = "mins") 
    }
}

```

### all species
```{r}
CT_test <- CT_act_date_proc[1:1000, ]

id_CT <- unique(CT_test$Station)
```


```{r}
CT_test$time_diff <- NA


for (pic in 1:(nrow(CT_test)-1)) {
 # for (i in id_CT) {
    if (CT_test$Station[pic+1] == CT_test$Station[pic]) {
      CT_test$time_diff[pic+1] <- difftime(time1 = CT_test$DateTimeOriginal[pic+1], time2 = CT_test$DateTimeOriginal[pic], units = "mins") 
    }
}

```


### test
```{r}

filterdate <- as.POSIXct("2020-10-21")
test1 <- CT_squirrel %>% 
  filter(Station == 1800) %>% 
  filter(Date == filterdate)

test1 %>% group_by(project_phase, Station) %>% 
  filter(time_diff < 1)


test2 <- CT_squirrel %>% 
  mutate(time_diff2 = case_when(
    is.na(time_diff) ~ 999,
    TRUE ~ time_diff)) %>% 
  group_by(project_phase, Station, Date) %>%
  filter(time_diff2 > 1) %>% 
  ungroup()
  

```

