---
title: 'Modelling Notebook: Squirrel WTimpact project'
author: "Sinah Drenske"
output:
  html_document:
    toc: yes
    toc_depth: '2'
    df_print: paged
  html_notebook:
    toc: yes
    toc_depth: 2
    code_folding: hide
    theme:
      bg: '#12162C'
      fg: '#F9F5C3'
      primary: '#BCBAC9'
      base_font: Calibri
      heading_font: Brandon Grotesque Black
editor_options: 
  markdown: 
    wrap: 72
---

# General information

Sinah Drenske, PhD Student\
IZW Berlin\
Department of Ecological Dynamics

and

Technical University Berlin\
Faculty VI Planning Building Environment\
Institute of Ecology\
Department of Planning-related Animal Ecology

Notebook started: 08.06.2022

## Project focus

XYZ...

## Collaborators

Julie Louvrier, Stephanie Kramer-Schadt

## Keyword List

List of keywords for the modelling notebook (from Ayllon et al. 2021 +
own terms)

+---------------------------------+---------------------------------+
| Modelling Notebook entry        | Modelling Notebook keyword      |
| tag/TRACE element               |                                 |
+=================================+=================================+
| Problem formulation             | Model purpose; Research         |
|                                 | questions                       |
+---------------------------------+---------------------------------+
| Model description               | Model development; Design       |
|                                 | decisions                       |
+---------------------------------+---------------------------------+
| Data evaluation                 | Parameterization; Patterns      |
+---------------------------------+---------------------------------+
| Conceptual model evaluation     | Conceptual design decisions     |
+---------------------------------+---------------------------------+
| Implementation verification     | Debugging; Software             |
|                                 | verification; Testing;          |
|                                 | Usability tools design          |
+---------------------------------+---------------------------------+
| Model output verification       | Output verification;            |
|                                 | Goodness-of-fit; Calibration;   |
|                                 | tests on\                       |
|                                 | environmental drivers           |
+---------------------------------+---------------------------------+
| Model analysis and application  | Sensitivity analysis;           |
|                                 | Uncertainty analysis;           |
|                                 | Robustness analysis;\           |
|                                 | Simulation experiment           |
+---------------------------------+---------------------------------+
| Model output corroboration      | Output corroboration;           |
|                                 | Validation                      |
+---------------------------------+---------------------------------+

# Topical index

link keywords to entries

# Master catalogue

List of locations of files most relevant to the project, with a
description of the file and folder taxonomy.

# Work log

## Entry Template

### General information

**Date**:\
**Author**: Sinah Drenske\
**Entry Type**:\
**TRACE tag**:\
**Keywords**:\
**Overview**:\
**Files**:

### Specific details

XYZ...

## 21.02.2023 - Meeting with Aimara, Stephanie

### General information

**Date**:\
**Author**: Sinah Drenske\
**Entry Type**:\
**TRACE tag**:\
**Keywords**:\
**Overview**:\
**Files**:

### Specific details

XYZ...

Was ist mit Stunden in denen es keine Eichhörnchenfotos gibt, aber Fotos
von den Prädatoren???

Warum sind meine Activity plots mit Fotos pro Stunde so unterschiedlich
von den Activity plots??

## 07.02.2023 - Meeting with Aimara, Marius and Stephanie

### General information

**Date**:\
**Author**: Sinah Drenske\
**Entry Type**:\
**TRACE tag**:\
**Keywords**:\
**Overview**:\
**Files**:

### Specific details

-   Environmental variables

    -   Dogs/ cats in gardens

+-------------+-------------+---------------+-------------------------+
| Garden type | Dogs Binary | Number of all | Number stations with    |
|             |             | stations      | squirrel pics           |
+=============+=============+===============+=========================+
| allotment   | 0           | 129           | 44                      |
+-------------+-------------+---------------+-------------------------+
| allotment   | 1           | 12            | 0                       |
+-------------+-------------+---------------+-------------------------+
| garden      | 0           | 463           | 161                     |
+-------------+-------------+---------------+-------------------------+
| garden      | 1           | 62            | 23                      |
+-------------+-------------+---------------+-------------------------+

: Dogs per garden type

+-------------+-------------+---------------+-------------------------+
| Garden type | Cats binary | Number of all | Number stations with    |
|             |             | stations      | squirrel pics           |
+=============+=============+===============+=========================+
| allotment   | 0           | 132           | 43                      |
+-------------+-------------+---------------+-------------------------+
| allotment   | 1           | 9             | 1                       |
+-------------+-------------+---------------+-------------------------+
| garden      | 0           | 396           | 146                     |
+-------------+-------------+---------------+-------------------------+
| garden      | 1           | 129           | 38                      |
+-------------+-------------+---------------+-------------------------+

: Cats per garden type

-   Mean value per project phase

    -   only per station

-   Models

    -   Confidence interval:

        -   ETI (equal tailed) or HDI (highest density)?

        -   95 or 89%?

        -   

## 31.01.2023 - Meeting with Aimara, Marius and Stephanie

### General information

**Date**: 31.01.2023\
**Author**: Sinah Drenske\
**Entry Type**:\
**TRACE tag**:\
**Keywords**:\
**Overview**:\
**Files**:

### Specific details

Questions:

-   Environmental variables

    -   Why are there NAs in Imperviousness and Population density?

    -   Why are there so many zeros in tree cover density?

    -   How should we handle NAs?

-   Models, Exploration:

    -   With or without stations where no pictures of squirrels were
        taken?
        -   WITH

Next steps:

-   Text: Little outline of the manuscript, RQ, H, figures + tables

    -   We know that urban variables are drivers for presence (But also
        for activity???), we want to have a look at temporal
        distribution

-   Datasets

    -   **Use only corrected data.** Remove the data with the time limit
        of 30 minutes (01, 03c, ...?)

    -   **With zeros per station, not without zeros**. When I calculate
        the number of pictures per station: Consider for each analysis
        also the stations with 0 pictures (also for activity plots etc.)

    -   

-   Environmental variables

    -   Tree cover density: Marius has a look at it and I ask Moritz
        again
    -   Plot old raster and new raster

-   Models + Activity

    -   Calculate the average number of pictures per hour per station
        (not the sum) + SD

    -   Plot the mean number with SD (for example in script 3b)

    -   Question for me? Will the results be so different? Test both

    -   Plot this against dogs, predators, (maybe urban and garden
        variables)

        -   Predators: also mean number of pictures per hour (but maybe
            also only presence absence?) for nocturnal animals there
            will be many zeros

-   Models:

    -   Until now I build different models for population density and
        distance to border. The correlation coefficient is 0.43. But now
        I will consider both of them in the same model. We will not
        consider correlations with a coefficient \< 0.7 (as long as it
        is only for one variable)

    -   We remove cats and dogs from the models, because there are no
        dogs in allotments and there is only 1 cat in an allotment

        -   We build a new model only for gardens where we consider cats
            and dogs

        -   Or we build a new variable with 3 levels (garden with dog,
            garden without dog, allotment without dog

    -   We have to find a way to calculate R^2^ for poisson models. This
        will be a Pseudo R^2^

    -   Results table: Add column for delta WAIC, order the models by
        ascending WAIC

## 19.01.2023 - Meeting with Aimara and Marius

### General information

**Date**: 19.01.2023\
**Author**: Sinah Drenske\
**Entry Type**:\
**TRACE tag**:\
**Keywords**:\
**Overview**:\
**Files**:

### Specific details

#### TOPs

-   Time differences

    -   Should I calculate the time difference twice? Because now the
        values between the entries do not match, since values with a
        difference of less than one minute were previously deleted.

    -   Should I only calculate the time difference between individual
        squirrel sightings or also for other species? I did it for all
        of them in order to delete those with a difference of less than
        one minute there as well (we should have a look at the table
        with the differences for the Raccoon for this: Station 277,
        07.10.2018 ca. 03:50)

    -   And then I calculate again the difference between Predator to
        Squirrel, but not the other way around and not between other
        species. Right?

    -   I haven't finished that yet, but my approach would be: First
        split into one dataset per predator (so only Squirrel-Fox,
        Squirrel-Raccoon etc.) then group again by Project phase and
        Stations and then check if CT\$Species[t] == "Predator" and
        CT\$Species[t+1] == "Squirrel", then calculate the difference.

-   Environmental data

    -   Moritz prepared it for me. I would delete the other variables
        now from the raw data folder. Right?

    -   Moritz gave me the file "districs" for the city border. Do you
        know how to merge this or should I ask him again exactly for the
        city border (it might be easier)?

    -   I tried to merge the data (but only quickly and copied a few
        functions), but now there are black dots in the feature of the
        city border... What am I doing wrong?

    -   Imperviousness of Marius is still a lot lower (Script 2a)

    -   Population density by Marius contains NaN values - why? how?

    -   Distance to border looks perfect! (With the dataset provided by
        Aimara)

-   Data

    -   Should dogs and cats (binary) be factors from the start? or does
        a correlation plot with dogs and cats make sense?

-   Style

    -   Activity plots: Radial or lines?

    -   Activity plots: Pics per hour enough?

    -   2b: Barcharts (Garden data exploration): Barchart or percent
        stacked barchart

## 10.01.2023 - Meeting with Stephanie, Aimara, Marius

### General information

**Date**: 10.01.2023\
**Author**: Sinah Drenske\
**Entry Type**:\
**TRACE tag**:\
**Keywords**:\
**Overview**:\
**Files**:

### Specific details

#### TOPs

1.  Environmental variables: -

    1.  differences between Marius and Julies calculations. Distance to
        border, Human population density, imperviousness (We work on it)

    2.  Aimara: newer data about noise? (Aimara will check this)

    3.  2b: Does the correlation matrix makes sense? How should I test
        the correlation for factors? (STILL OPEN)

2.  New variables: dogs, cats, trees of interest

    1.  There are only 30 plots without trees of interest. Is that a
        problem?

    2.  How should I test the correlation of dogs/cats/trees of interest
        with the other variables? Is the correlation matrix enough?

    3.  I would possibly split deciduous and coniferous trees. As
        conifers have been identified as good predictors in other
        studies (but these were not about pictures, but about CMR).

3.  Glms

    1.  Formulation correct?

    2.  What is the correct formulation of the null model?

        1.  n_pics \~1

            or

            n_pics \~ 1 + Season + lockdown

    3.  What does it mean if the intercept of the null model is
        significant?

    4.  Should I include stations as random intercept? (1 \| Station)

4.  Plots

    1.  Activity plots: Lines or radial?

5.  Next steps

    1.  Writing: I have not started yet. But I want to start this week.

    2.  Models with time limit

    3.  Models for the daily patterns, predator presence (see
        31.10.2022)

#### Next steps

-   General pattern

    -   Overlap plots of activity with and without dogs per season

    -   Calculate r\^ and mean activity time

    -   Drop trees of interest as variable

-   Analyse the correlation of dogs and cats with the other
    environmental variables

    -   Plot dogs/cats against season, project phase and the garden
        variables

    -   Raincloud plots/violin plots or boxplots

    -   Map of all stations and stations with dogs/cats

-   Daily patterns

    -   Separate models per season (= spring and autumn not together in
        one model)

    -   Response: Nr of pictures per day, nr of pictures per hour, r hat
        (r\^), time shift of mean/mode activity time

    -   Plot of r\^ against time shift

    -   Include (1\|Station) as random variable

## 05.01.2023 - R work GLMs

### General information

**Date**:05.01.2023\
**Author**: Sinah Drenske\
**Entry Type**: Notes for R and questions\
**TRACE tag**:\
**Keywords**:\
**Overview**:\
**Files**:

### Specific details

For some stations (like Station 1919) there are NAs for the
environmental variables calculated by Marius - in the table of the
environmental covariates by Julie are less stations than in the table of
the CT histories. I will retrieve the missing information the table of
all covariates, than Marius (or I) has to redo the analysis in 2a. -
SOLUTION: These stations are outside of Berlin or have wrong
coordinates. The respective rows (pictures) will be deleted from the
table.

What does it mean if the intercept of the null model is significant?

What is the correct formulation of the null model?

n_pics \~1

or

n_pics \~ 1 + Season + lockdown

SHould I inlcude stations as random intercept? (1 \| Station)

## 19.12.2022 - R Work

### General information

**Date**:19.12.2022\
**Author**: Sinah Drenske\
**Entry Type**: Notes for R\
**TRACE tag**:\
**Keywords**:\
**Overview**:\
**Files**:

### Specific details

I accidentally deleted the labbook and other files when I changed
something in the GitHub repository. I was able to restore most of the
files.

I reorganised the R Scripts

## 29.11.2022 - Meeting with Stephanie

### General information

**Date**:\
**Author**: Sinah Drenske\
**Entry Type**: Meeting notes\
**TRACE tag**: Other\
**Keywords**: Meeting\
**Overview**:\
**Files**:

### Specific details

Plots of the activity in relation to different environmental variables

## 24.11.2022 - Meeting with Aimara and Julie

### General information

**Date**: 24.11.2022\
**Author**: Sinah Drenske\
**Entry Type**: Meeting notes\
**TRACE tag**: Other\
**Keywords**: Meeting, Text, Code\
**Overview**:\
**Files**:

### Specific details

#### Next steps

-   What variables are used in the literature?

-   Replace "season" with "project phase"

-   nice plots and maps

-   Next meeting: Thursday, 05.01.2023 13:30

#### Environmental variables

-   For an overview of the data, one should only plot x=station.

-   In addition, the data from Marius should be plotted against the data
    from Julie/Aimara (is in the "Meet" script and must still be
    inserted at the appropriate place).

-   Then we could make a first assessment of the variables, for which x
    = n (nr of pictures), y = environmental variable. But this would
    only be done in the script in which we decide which variables we
    actually use (which script would that be?)

-   After the first overview we use the following variables:

    -   urban level:

        -   imperviousness (Raster von Marius bzw. aktuellere Daten)

        -   tree cover (newer data)

        -   distance to border (right calculation - Julie or Marius)

        -   Pop density from 2019 (Marius or I have to redo the
            analysis)

        -   noise (newer data?)

    -   garden level:

        -   garden type

        -   garden size

        -   from the Table with ALL covariates:

        -   dog

        -   cat (these 2 will be binary: no cat/dog = 0, yes/nachts im
            Haus = 1)

        -   trees of interest (Summary of the following columns:
            baeume_Buchen, Eichen, Nadel, Nuss, Obst. Is one of them
            present in the garden = 1, otherwise = 0)

-   I have to test the correlation of the garden variables (all) for
    dogs and cats: plot of all gardens with cats/dogs with the other
    garden variables

-   plot all variables against each other (e.g. garden size \~ type of
    garden)

-   Use group-equal() - HOW?

#### Run the models

-   Model characteristics

    -   scale all numeric variables: scale(variable)

    -   binary variables: as factor

    -   family = Poisson

    -   Response: nur of pictures of squirrels - with and without time
        limit (30 min)

-   We build 3 different models per approach (so 6 models in total)

    -   Full model: activity \~ urban variables + garden variables +
        season + lockdown

    -   Urban_mod: activity \~ urban variables + season + lockdown

    -   Garden_mod: activity \~ garden variables + season + lockdown

-   Calculate: AIC, R\^2, effect sizes, proper effects of the covariates
    (pos or neg), Residuals

## 17.11.2022 - Meeting with Aimara, Julie and Marius

### General information

**Date**: 17.11.2022\
**Author**: Sinah Drenske\
**Entry Type**: Meeting notes\
**TRACE tag**: Other\
**Keywords**: Meeting, Text, Code\
**Title**: Meeting with Aimara, Julie and Marius\
**Overview**:\
**Files**:

### Specific details

#### Next Meeting

24.11. 13:30 Meeting with Julie and Aimara

#### Next steps

-   Develop hypothesis

    -   More squirrel activity during lockdown, because people were
        feeding the squirrels (LIT)

        -   or less activity because of the increased human presence?
            Less activity in areas with high imperviousness

    -   But also less activity in areas near green spaces because the
        squirrels can avoid gardens? (areas with low human population
        density + low distance to open green areas)

    -   squirrels avoid gardens where dogs or cats live

    -   squirrels are more active during times when people are probably
        not at home

    -   Sunrise???? Squirrels activity depends on the sunrise (can I
        analyse that?)

    -   Squirrels avoid a garden when a cat has visited it. Raccoons,
        martens and foxes are rather nocturnal, thus there is no
        particularly long waiting time to be expected

        -   Or: squirrels generally avoid gardens where potential
            predators are present (even if some are nocturnal)

    -   Squirrel activity is higher in areas with higher distance to
        roads (or on the contrary, less activity is observed there, as
        they tend to move to open green areas

    -   Squirrel acitivty is higher in areas with high tree coverage

    -   Fence height, compost have no effect

    -   Less acitivty in areas with higher noise level, traffic volume,
        human population density, imperviousness (but I think many of
        them are correlated)

    -   Garden size ? I am not sure...

-   Check literature: which environmental covariates are used in other
    studies?

-   Plots for the environmental covariates and the number of pictures -
    how does the number of pictures change with tree cover, fence
    height, etc.

-   Add a column for the season (spring vs autumn) - then I have to
    rename the column season (1-5) maybe to project_phase (according to
    the table with env covariates of the camera stations)

-   Plot of the camera stations

-   Marius: calculates the distance to border with focal mean +
    correlation tests of the environmental covariates

-   ~~Julie: will send the table with more covariates (pets, tree
    composition etc.)~~

#### Other notes

-   Resolution of the environmental data should be 100m

-   Julie made the activity plots with ggplot

-   Ideas: Can I calculate the mean activity hour per season with
    group_by(species, season) %\>% summarize(mean_time =
    mean(Time))?????

-   **End of February**: First draft of the manuscript

## 31.10.2022 - Meeting with Aimara and Marius

### General information

**Date**: 31.10.2022\
**Author**: Sinah Drenske\
**Entry Type**: Meeting notes\
**TRACE tag**: Other\
**Keywords**: Meeting, Text\
**Title**: Meeting with Aimara and Marius\
**Overview**:\
**Files**:
C:\Users\drenske\Nextcloud\Projects\sciurus\_vulgaris_b\_cttemp_drenske_s\docs\literature

### Specific details

#### Caveats/Possible problems

-   Check the time zone of the camera traps (table?)

-   Plot all camera traps: Are all in Berlin?

-   correlation of environmental covariates (Script + Data by
    **Marius**)

-   nr pictures independent? They are not. Run models with a) all
    pictures and b) only pictures where there are 30mins between 2
    pictures of a squirrel

#### To Do - Part 1: General description

-   Data: WTimpact, autumn 2018-autumn 2020, 5 seasons

1.  Summaries:\
    Per season: Nr pictures per season, activity patterns (peak time, nr
    pictures over the day), average for all individuals per season

    1.  For now especially for squirrels

    2.  Later for the predators (fox, cat, raccoon, marten)

2.  Test:

    1.  Check the Japanese Paper (Uchida et al. 2016)

    2.  Activity \~ season + covid + environmental covariates (tree
        cover, garden type, ...)

        1.  Environmental covariates: garden scale + urban scale (100m)

        2.  Define activity: Check Japanese Paper (peak activity time or
            nr of pictures)

#### To Do - Part 2: Daily patterns

-   Try to include each predator on its own in the models, do not pool
    them. If we have enough data of a species. If we have not enough
    data of species - pool them together as predators

-   test: activity (nr pictures) \~ season + covid + (presence of
    predator OR, if we have enough data, presence of fox + cat +
    marten + raccoon) + (1 \| ID camera trap)

    -   Presence of a predator/species: time after a squirrel visits a
        garden after a predator was there - night before

        -   night: 9pm-5am, day: 5am-9pm

        -   predator morning: 5am-9am

        -   include night + morning as different variables in the model.
            if that does not work, we try it in different models

-   test: time spent (maybe same as nr pictures) \~ minutes to sunrise +
    season + covid + presence of predator in the night/ or if there is
    enough data: presence of fox, cat, marten, raccoon) + presence of
    poredator in the morning + (1\|ID -- garden = camera trap ID)

-   time of delay (Julies Paper): Here, there should be an interval of
    at least 30 minutes between images of the same species.

    -   Analysis on a daily basis (reset on midnight)

    -   Squirrel - first species after the squirrel = time since
        predator

    -   Predator - squirrel = time to predator

    -   Squirrel - squirrel = Time to next squirrel, at least 30 minutes

    -   Model: time of delay \~ Fox + squirrel + marten + cat +
        raccoon + (1 \| ID camera trap)

#### Time frame

-   Next meeting: 16.11. (Wednesday): Seasonal analyses finished
    (general part + summaries)

-   Mid January: Finish data analysis 31.03.2023: Submit article

## 27.10.2022 - Abstract submission

### General information

**Date**: 27.10.2022\
**Author**: Sinah Drenske\
**Entry Type**: Meeting notes\
**TRACE tag**: Other\
**Keywords**: Meeting, Text\
**Title**: Submitting the abstract\
**Overview**:\
**Files**:
C:\Users\drenske\Nextcloud\Projects\sciurus\_vulgaris_b\_cttemp_drenske_s\docs\manuscript\Drenske\_et_al-2023-Activity_Squirrels_20221025_SUBMIT

### Specific details

I submitted the preliminary abstract :)

## 19.10.2022 - Meeting mit Aimara

### General information

**Date**: 19.10.2022\
**Author**: Sinah Drenske\
**Entry Type**: Meeting notes\
**TRACE tag**: Other\
**Keywords**: Meeting, Text\
**Title**: Meeting with Aimara for the Abstract for FEE\
**Overview**:\
**Files**:
C:\Users\drenske\Nextcloud\Projects\sciurus\_vulgaris_b\_cttemp_drenske_s\docs\manuscript\Drenske\_et_al-2023-Activity_Squirrels_20221025_SUBMIT

### Specific details

Activity of Squirrels in urban environments

1.  General description -\> (average per) season -\> Breeding season vs.
    winter preparation season + Environmental covariates

    1.  and everything for the potential predators (marten, raccoon,
        fox, cats)

2.  Daily patterns -\> interactions -\> squirrels + potential predators

    1.  Intensity, peak activity, time

    2.  Time of delay: squirrel -- squirrel, squirrel -- predator

**Leading to the following research questions**

1.  We investigate seasonal differences of activity patterns of red
    squirrels in the urban environment

2.  And how urbanization alters species interactions with potential
    predators, determining niche partitioning

## 13.08.2022 - R Work

### General information

**Date**:13.08.2022\
**Author**: Sinah Drenske\
**Entry Type**: Code\
**TRACE tag**:\
**Keywords**:\
**Title**:\
**Overview**:\
**Files**:

### Specific details

QUestion: Script 02, function calculate_delta, part with diff &
difftime: why do we calculate negative differences? Why the first
picture - later picute and not later picture - picture before?

## 03.08.2022

### General information

**Date**:03.08.2022\
**Author**: Sinah Drenske\
**TRACE tag**:\
**Keywords**:\
**Title**: Preparation of the temporal analyses\
**Overview**:Review of Julies script and adaptation to the squirrel
project\
**Files**:

### Specific details

What I did: I worked on script 2, the preparation for the temporal
analyses. I changed some things for example I used the hms time object
to calculate the time differences. Maybe that will cause problems later.
For example during the function that is not working. Maybe I could also
write something more efficient? But at first I need to understand what
the function does. Maybe I should run Julies script and see how its
working

Questions: Am I using the right dataset? After looking for a while at
the scripts I am so confused that I am not sure if I am using still the
right CT dataset. And is the delta of 30 min included in this dataset or
not?????

Idea: replace German species names directly at the beginning in Script
01. Then we have to change it in all other scripts

## 02.08.2022

### General information

**Date**: 02.08.2022\
**Author**: Sinah Drenske\
**Entry Type**: Code\
**TRACE tag**:\
**Keywords**:\
**Title**: Refreshing memories\
**Overview**: Review scripts and data\
**Files**:

### Specific details

I want to get familiar again with the data and the scripts and to
continue my work on it.

Decision: For now I will not work on datasets for the jsdm (because I am
not sure if we will develop one for this study)

Ideas: defining time windows depending on the hour of the day (for
example: 04-10 am - morning, 10-3pm - noon, 3-7pm - afternoon, 7-11pm -
evening, 11pm-04am - night) Characterise the stations better - where are
they, what are the characteristics and so on. Because if more stations
are under specific conditions, we will of course see more animals there

For all (study) species: define hours per day. When are they active?

For squirrels (or all species?): activity during the seasons (ist aber
auch eigentlich schon in einem der ersten plots vermerkt) Aber
vielleicht genauer ansehen? Wann sind Eichhörnchen in den Seasons vor
allem aktiv also zu welchen uhrzeiten? Gibt es da Unterschiede?

## 08.06.2022

### General information

**Date**:08.06.2022\
**Author**: Sinah Drenske\
**Entry Type**: Labbook Setup\
**TRACE tag**:\
**Keywords**:Setup\
**Title**: Setting up the modelling notebook\
**Overview**:Designing layout and structure of the modelling notebook\
**Files**:

### Specific details

I have started the modelling notebook and will now record all progress
on this project here. Why did we choose the specific species? Squirrels
are our study species and we choose each possible predator where we have
data from even if the probability to get eaten by this animal is low.
therefore we choose cats, martens, foxes and raccoons as possible
predators
