---
title: "Your Project: Data Preparation" ## name of your project and analysis step
description: |
    The aim of this study is...
author:
    ## author information; single arguemnts can be deleted if not needed
    - name: "John Smith"
      url: https://izw-berlin.de/en/john-smith-en.html  
      affiliation: Leibniz Institute for Zoo and Wildlife Research
      affiliation_url: https://izw-berlin.de/en/
      orcid_id: 0000-0000-0000-0000
    - name: "Jane Doe"
      url: https://janedoe.com
      affiliation: Leibniz Institute for Zoo and Wildlife Research
      affiliation_url: https://izw-berlin.de/en/
    ## add more authors with the same intendation and styling if needed 
    ## a new author always starts with a hyphen!
date: "`r Sys.Date()`"
output: 
    distill::distill_article:
        highlight: kate      ## styling of code
        code_folding: false  ## if `true` you can expand and shrink code chunks
        toc: true            ## if `true` adds a table of content
        toc_depth: 2         ## level to be displayed in the table of content
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      dev = "ragg_png", fig.width = 9, fig.height = 6, dpi = 600, retina = 1)
Sys.setlocale("LC_TIME", "C")
```

* **Research question:**
* **Study area:**
* **Data:** 


# Setup

```{r packages}
#remotes::install_github("EcoDynIZW/d6")
d6::simple_load(c("cowplot", 
                  "dplyr",
                  "ggplot2", 
                  "ggspatial", 
                  "grid",
                  "here",
                  "png", 
                  "raster", 
                  "rnaturalearth", 
                  "rnaturalearthdata",
                  "sf",
                  "terra", 
                  "viridis"
)) 
```

```{r theme}
theme_set(
  theme(
    #legend.position = "none",
    #panel.grid = element_blank(),
    #panel.background = element_rect(fill = "white"),
    panel.background = element_rect(fill = NULL, color = "grey80"),
    panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
    plot.margin = margin(6, 10, 4, 4),
    axis.title = element_blank(),
    axis.ticks = element_line(colour = "black", linewidth = 1.5),
    axis.ticks.length = unit(0.2, "cm"),
    title = element_text(family = "Zilla Slab", size = 15), # axis
    axis.text = element_text(family = "Roboto", size = rel(0.87)))) # axis ticks


# my_theme <- theme(
#     legend.position = "none",
#     panel.grid = element_blank(),
#     panel.background = element_rect(fill = "white"),
#     panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
#     plot.margin = margin(6, 10, 4, 4),
#     axis.ticks = element_line(colour = "black", linewidth = 1.5),
#     axis.ticks.length = unit(0.2, "cm"), 
#     title = element_text(family = "Zilla Slab", size = 15),
#     axis.text = element_text(family = "Roboto", size = rel(0.87)))
```


# Data

```{r data}
## impervious surface
imperv <- rast(here::here("data-raw/geo-raw/imperviousness_berlin_copernicus_raster_10m_2018_3035/imperviousness_berlin_copernicus_raster_10m_2018_3035.tif"))

## water bodies
water <- st_read(here::here("data-raw/geo-raw/waterbodies_Berlin_25833.gpkg")) %>% 
  st_transform(crs = 3035) %>% 
  st_union()

## berlin border
berlin <- st_read(here::here("data-raw/geo-raw/berlin_city_border_25833.gpkg")) %>% 
  st_transform(crs = 3035) %>% 
  st_union()


##loading the environmental variables with camera coordinates
env_var <- readRDS(here::here("output/data-proc/01_overall_activity/env_var_binary_species_20230305.RDS"))
head(as.data.frame(env_var))
```


```{r spatial}
# make it spatial
ct_spatial <- st_as_sf(x = env_var,
           coords = c("Long","Lat"), # name the columns with the coordinates
           remove = F, # dont remove long lat columns
           crs = 32633) %>% # crs of the points
  st_transform(crs = 3035) %>% 
  mutate(xcoord = Long, ycoord = Lat)  ## correct the names. Long and Lat should be used only for degrees
```

First plot
```{r spatial}
plot(imperv)
plot(st_geometry(ct_spatial), add = TRUE, col = "blue", pch = 16)
```

## aggregate raster for faster plotting
```{r}
imperv_250 <- aggregate(imperv, fact = 25, fun = mean, na.rm = TRUE)

# get in data frame format
imperv_df <- as.data.frame(imperv_250, xy = TRUE)
colnames(imperv_df)[3] <- "imperv"

imperv10_df <- as.data.frame(imperv, xy = TRUE)
colnames(imperv10_df)[3] <- "imperv"
```

## create base map
```{r}
RColorBrewer::brewer.pal(n = 8, name = "Dark2")
magma(n = 4, end = 0.9)

# pal_4 <- c("#303B4A", "#E4CAA5", "#4D6476", "#837461") # , "#C83649"
# Tol_bright <- c('#EE6677', '#228833', '#4477AA', '#CCBB44', '#66CCEE', '#AA3377', '#BBBBBB')
# Okabe_Ito <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#000000")
# 
# pal_phase <- c('#E4CAA5', '#EE6677', '#228833', '#CCBB44')
pal_phase2 <- c( "#0072B2", "#D55E00", "#CC79A7", "#000000")


pal_alpha <- c("1" = 1, "0" = 0.7)

(map1 <- ggplot() +
    geom_raster(data = imperv_df, aes(x = x, y = y, fill = imperv)) +
    scale_fill_viridis(option = "E", na.value = NA, direction = -1, 
                       begin = 0.2, end = 0.6, alpha = 0.4, 
                       name = "Imperviousness") +
    geom_sf(data = berlin, colour = "grey70", lwd = 1.2, fill = NA) +
    geom_sf(data = water, fill = "lightblue3", colour = "transparent") +
    geom_sf(data = ct_spatial, aes(colour = project_phase, pch = project_phase, alpha = squirrels_cam_binary), 
            size = 2) +
    geom_sf(data = ct_spatial %>% 
              filter(squirrels_cam_binary == 1), aes(pch = project_phase), 
             size = .5, col = "white") +
    scale_colour_manual(values = rev(pal_phase2), name = "Phase", 
                        labels = c("Spring 19", "Autumn 19", "Spring 20", "Autumn 20")) +
    scale_shape_manual(name = "Phase",
                     values = c(16,17,18,15),
                     labels = c("Spring 19", "Autumn 19", "Spring 20", "Autumn 20")) +
    scale_alpha_manual(values = pal_alpha) +
    annotation_north_arrow(which_north = "true", location = "bl",
                            pad_x = unit(0.3, "cm"), pad_y = unit(1, "cm"),
    height = unit(1, "cm"),
    width = unit(0.6, "cm")) +
    annotation_scale(text_cex = 1.5) +
    guides(shape = guide_legend(order = 1), 
           colour = guide_legend(order = 1, 
                                 override.aes = list(colour = rev(c("#0072B2", "#D55E00", "#CC79A7", "#000000")), 
                                                  size = c(3,3,4,3))),
           fill = guide_legend(order = 2), 
           alpha = "none") +
   theme_minimal() +
  theme(
    # panel.grid = element_blank(),
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = NULL, color = "grey80"), 
    axis.title = element_blank(),
    legend.position = c(0.85,0.85),
    legend.title = element_text(face = "bold", size = 10),
    legend.text = element_text(size = 10),
    legend.key.size = unit(0.8,"lines"), 
    legend.box = "horizontal")
)
#"#000004FF" "#721F81FF" "#F1605DFF" "#FCFDBFFF"

```

```{r}
col_points <- c("#000004FF", "#641A80FF", "#DE4968FF", "#FECE91FF")
col_points2 <- c("#000004FF", "#641A80FF", "#277F8EFF", "#4AC16DFF")
RColorBrewer::brewer.pal(n = 8, name = "Dark2")
viridis(n = 8)
# c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D", "#666666")
 c("#440154FF", "#46337EFF", "#365C8DFF", "#277F8EFF", "#1FA187FF", "#4AC16DFF", "#9FDA3AFF", "#FDE725FF")
```

# NICE MAP SINAH
```{r}
# map_berlin <-
# ggplot() +
#   geom_raster(data = imperv_df, aes(x = x, y = y, fill = imperv)) +
#   scale_fill_viridis(option = "E", na.value = NA, direction = -1,
#                      begin = 0.2, end = 0.6, alpha = 0.4,
#                      name = "Imperviousness") +
#  # geom_sf(data = berlin, colour = "#c5c8d9", lwd = 1.2, fill = NA) +
#   geom_sf(data = water, fill = "lightblue3", colour = "transparent") +
#   geom_sf(data = ct_spatial, aes(colour = project_phase, pch = project_phase, alpha = squirrels_cam_binary),
#           size = 2) +
#   geom_sf(data = ct_spatial %>%
#             filter(squirrels_cam_binary == 1), aes(pch = project_phase),
#           size = .5, col = "white") +
#   scale_colour_manual(values = rev(col_points), name = "Phase",
#                       labels = c("Spring 19 - no Lockdown", "Autumn 19 - no Lockdown", 
#                                   "Spring 20 - Lockdown", "Autumn 20 - Lockdown")) +
#   scale_shape_manual(name = "Phase",
#                      values = c(16,17,18,15),
#                      labels = c("Spring 19 - no Lockdown", "Autumn 19 - no Lockdown", 
#                                   "Spring 20 - Lockdown", "Autumn 20 - Lockdown")) +
#   scale_alpha_manual(values = pal_alpha) +
#   annotation_north_arrow(which_north = "true", location = "bl",
#                          pad_x = unit(5.5, "cm"), pad_y = unit(0.2, "cm"),
#                          height = unit(1, "cm"),
#                          width = unit(0.6, "cm")) +
#   annotation_scale(text_cex = 1.5) #+
#   # guides(shape = guide_legend(order = 1),
#   #          colour = guide_legend(order = 1,
#   #                                override.aes = list(colour = rev(col_points),
#   #                                                 size = c(3,3,4,3))),
#   #          fill = guide_legend(order = 2),
#   #          alpha = "none")

#map_berlin

##################################

map_berlin2 <-
  ggplot() +
  geom_raster(data = imperv10_df, aes(x = x, y = y, fill = imperv)) +
  scale_fill_viridis(option = "rocket", na.value = NA, direction = -1,
                     #begin = 0.2, 
                     end = 0.9, 
                     alpha = 0.3,
                     name = "Imperviousness") +
  # geom_sf(data = berlin, colour = "#c5c8d9", lwd = 1.2, fill = NA) +
  geom_sf(data = water, fill = "lightblue3", colour = "transparent") +
  geom_sf(data = ct_spatial, aes(colour = project_phase, pch = project_phase, alpha = squirrels_cam_binary),
          size = 2) +
  geom_sf(data = ct_spatial %>%
            filter(squirrels_cam_binary == 1), aes(pch = project_phase),
          size = .5, col = "white") +
  scale_colour_manual(values = rev(col_points2), name = "Phase",
                      labels = c("Spring 19 - no Lockdown", "Autumn 19 - no Lockdown", 
                                 "Spring 20 - Lockdown", "Autumn 20 - Lockdown")) +
  scale_shape_manual(name = "Phase",
                     values = c(16,17,18,15),
                     labels = c("Spring 19 - no Lockdown", "Autumn 19 - no Lockdown", 
                                "Spring 20 - Lockdown", "Autumn 20 - Lockdown")) +
  scale_alpha_manual(values = pal_alpha, name = "Squirrels", labels = c("Yes", "No")) +
  annotation_north_arrow(which_north = "true", location = "bl",
                         pad_x = unit(0.3, "cm"), pad_y = unit(0.7, "cm"),
                         height = unit(1, "cm"),
                         width = unit(0.6, "cm")) +
  annotation_scale(text_cex = 1.5) +
  guides(shape = guide_legend(order = 1),
         colour = guide_legend(order = 1,
                               override.aes = list(colour = rev(col_points2),
                                                   size = c(3,3,4,3)))#,
         #fill = guide_legend(order = 2)#,
         #alpha = "none"
         ) +
  scale_x_continuous(breaks = seq(13.1, 13.7, by = 0.2)) + 
  scale_y_continuous(breaks = seq(52.35, 52.70, by = 0.10)) 

map_berlin2

#################################


# map_berlin4 <-
#   ggplot() +
#   geom_raster(data = imperv_df, aes(x = x, y = y, fill = imperv)) +
#   scale_fill_viridis(option = "rocket", na.value = NA, direction = -1,
#                      #begin = 0.2, 
#                      end = 0.9, 
#                      alpha = 0.3,
#                      name = "Imperviousness") +
#   # geom_sf(data = berlin, colour = "#c5c8d9", lwd = 1.2, fill = NA) +
#   geom_sf(data = water, fill = "lightblue3", colour = "transparent") +
#   geom_sf(data = ct_spatial, aes(colour = project_phase, pch = project_phase, alpha = squirrels_cam_binary),
#           size = 2) +
#   geom_sf(data = ct_spatial %>%
#             filter(squirrels_cam_binary == 1), aes(pch = project_phase),
#           size = .5, col = "white") +
#   scale_colour_manual(values = rev(col_points2), name = "Phase",
#                       labels = c("Spring 19 - no Lockdown", "Autumn 19 - no Lockdown", 
#                                  "Spring 20 - Lockdown", "Autumn 20 - Lockdown")) +
#   scale_shape_manual(name = "Phase",
#                      values = c(16,17,18,15),
#                      labels = c("Spring 19 - no Lockdown", "Autumn 19 - no Lockdown", 
#                                 "Spring 20 - Lockdown", "Autumn 20 - Lockdown")) +
#   scale_alpha_manual(values = pal_alpha, name = "Squirrels", labels = c("Yes", "No")) +
#   annotation_north_arrow(which_north = "true", location = "bl",
#                          pad_x = unit(0.3, "cm"), pad_y = unit(0.7, "cm"),
#                          height = unit(1, "cm"),
#                          width = unit(0.6, "cm")) +
#   annotation_scale(text_cex = 1.5) +
#   guides(shape = guide_legend(order = 1),
#          colour = guide_legend(order = 1,
#                                override.aes = list(colour = rev(col_points2),
#                                                    size = c(3,3,4,3)))#,
#          #fill = guide_legend(order = 2)#,
#          #alpha = "none"
#   ) +
#   scale_x_continuous(breaks = seq(13.1, 13.7, by = 0.2)) + 
#   scale_y_continuous(breaks = seq(52.35, 52.70, by = 0.10)) 
#   
#   
#   map_berlin4

################

# map_berlin3 <-
#   ggplot() +
#   geom_raster(data = imperv_df, aes(x = x, y = y, fill = imperv)) +
#   scale_fill_viridis(option = "D", alpha = 0.4, direction = -1, end = 0.95,
#                      name = "Imperviousness") +
#   geom_sf(data = water, fill = "lightblue3", colour = "transparent") +
#   geom_sf(data = ct_spatial, aes(colour = project_phase, pch = project_phase, alpha = squirrels_cam_binary),
#           size = 2) +
#   geom_sf(data = ct_spatial %>%
#             filter(squirrels_cam_binary == 1), aes(pch = project_phase),
#           size = .5, col = "white") +
#   scale_colour_manual(values = rev(col_points), name = "Phase",
#                       labels = c("Spring 19 - no Lockdown", "Autumn 19 - no Lockdown",
#                                  "Spring 20 - Lockdown", "Autumn 20 - Lockdown")) +
#   scale_shape_manual(name = "Phase",
#                      values = c(16,17,18,15),
#                      labels = c("Spring 19 - no Lockdown", "Autumn 19 - no Lockdown",
#                                 "Spring 20 - Lockdown", "Autumn 20 - Lockdown")) +
#   scale_alpha_manual(values = pal_alpha) +
#   annotation_north_arrow(which_north = "true", location = "bl",
#                          pad_x = unit(5.5, "cm"), pad_y = unit(0.2, "cm"),
#                          height = unit(1, "cm"),
#                          width = unit(0.6, "cm")) +
#   annotation_scale(text_cex = 1.5)  +
# guides(shape = guide_legend(order = 1),
#          colour = guide_legend(order = 1,
#                                override.aes = list(colour = rev(col_points),
#                                                 size = c(3,3,4,3))),
#          fill = guide_legend(order = 2),
#          alpha = "none")
# 
#  map_berlin3




```

# TEST
```{r}
ggplot(dat, aes(x = xvar, y = yvar, shape = cond, 
                colour = cond), size = 2.5) + 
  geom_point(alpha = 1) +
  geom_point(data = g1, colour = "blue", size = 4, show_guide = FALSE)

ggplot(dat, aes(x = xvar, y = yvar, shape = cond, 
                colour = cond), size = 2.5) + 
  geom_point(alpha = 1) +
  geom_point(data = g1, aes(colour = "Point 15", shape = "Point 15"), size = 4) +
  scale_shape_manual(values = c(16, 17, 17) ) +
  scale_color_manual(values = c("pink", "turquoise", "blue") ) +
  guides(color = guide_legend( override.aes = list(size = c(1.5, 1.5, 4) ) ) )
```
## TEST ENDE


```{r}
ggplot() +
    geom_raster(data = imperv_df, aes(x = x, y = y, fill = imperv)) +
    scale_fill_viridis(option = "E", na.value = NA, direction = -1, 
                       begin = 0.2, end = 0.6, alpha = 0.4, 
                       name = "Imperviousness") +
    geom_sf(data = berlin, colour = "grey70", lwd = 1.2, fill = NA) +
    geom_sf(data = water, fill = "lightblue3", colour = "transparent") +
    geom_sf(data = ct_spatial, aes(colour = project_phase, pch = project_phase, alpha = squirrels_cam_binary), 
            size = 2) +
    geom_sf(data = ct_spatial %>% 
              filter(squirrels_cam_binary == 1), aes(pch = project_phase), 
             size = .5, col = "white") +
    scale_colour_manual(values = rev(pal_phase2), name = "Phase", 
                        labels = c("Spring 19", "Autumn 19", "Spring 20", "Autumn 20")) +
    scale_shape_manual(name = "Phase",
                     values = c(16,17,18,15),
                     labels = c("Spring 19", "Autumn 19", "Spring 20", "Autumn 20")) +
    scale_alpha_manual(values = pal_alpha) +
    annotation_north_arrow(which_north = "true", location = "bl",
                            pad_x = unit(0.3, "cm"), pad_y = unit(1, "cm"),
    height = unit(1, "cm"),
    width = unit(0.6, "cm")) +
    annotation_scale(text_cex = 1.5) +
    guides(shape = guide_legend(order = 1), 
           colour = guide_legend(order = 1, 
                                 override.aes = list(colour = rev(c("#0072B2", "#D55E00", "#CC79A7", "#000000")), 
                                                  size = c(3,3,4,3))),
           fill = guide_legend(order = 2), 
           alpha = "none")
```


## Prettify the map
```{r}
## load images
img_squirrel <- readPNG("data-raw/squirrel_silhouette.png")
g_squirrel <- rasterGrob(img_squirrel, interpolate=TRUE)

## tree
img_tree <- readPNG("data-raw/tree.png")
g_tree <- rasterGrob(img_tree, interpolate=TRUE)

## camera
img_cam <- readPNG("data-raw/camera_img.png")
g_cam <- rasterGrob(img_cam, interpolate=TRUE)



## add images
# add images
st_bbox(berlin)

(map2 <- map1 +
    annotation_custom(g_tree, xmin = 4571452 , xmax = 4579152 , ymin = 3269495 , ymax = 3278395) +
    # annotation_custom(g_cam, xmin = 4573452 , xmax = 4577152 , ymin = 3266495 , ymax = 3280695) +
    annotation_custom(g_squirrel, xmin = 4569452 , xmax = 4573552 , ymin = 3252495 , ymax = 3290695) 
)
  
# ggsave(plot = map2, 
#        "plots/Fig1_map_studyArea_opt1.png", 
#        dpi = 600, height = 7, width = 7)
```

```{r}
## just the squirrel

squirrel_plot <- ggplot() +
  geom_point(aes(x =seq(1:10), y = seq(1:10)), 
             col = NA, fill = NA) +
  annotation_custom(g_squirrel, xmin = 2 , xmax = 6 , ymin = 1 , ymax = 4) +
  annotation_custom(g_tree, xmin = 5 , xmax = 10 , ymin = 1 , ymax = 10) +
  annotation_custom(g_cam, xmin = 6.7 , xmax = 7.7 , ymin = 3 , ymax = 4) +
  theme_void()

squirrel_plot

```

## map Europe

```{r}
world <- ne_countries(scale = "medium", returnclass = "sf")
europe <- world %>% 
  filter(continent  == "Europe")

europe_crop <- europe %>% 
   st_make_valid() %>% 
    st_crop(xmin = -15, ymin = 25, xmax = 30, ymax = 55) # xmin = -25, ymin = 25, xmax = 50, ymax = 70

europe_crop2 <- europe %>% 
   st_make_valid() %>% 
    st_crop(xmin = -25, ymin = 25, xmax = 50, ymax = 70) # xmin = -25, ymin = 25, xmax = 50, ymax = 70

centroid_berlin <- berlin %>% 
  st_transform(crs = 4326) %>% 
  st_centroid()
```


```{r}
(eu_map <- ggplot() +
    geom_sf(data = europe_crop2, col = "black", fill = "grey90") +
    geom_sf(data = centroid_berlin, size = 6, pch = 22, linewidth = 3, fill = "red", col = "red") +
    geom_sf(data = centroid_berlin, col = "red", size = 4, pch = 22, fill = "grey90") +
    coord_sf(xlim = c(-25,51.5), ylim = c(35,71), expand = FALSE) 
)

(eu_map2 <- ggplot() +
    geom_sf(data = europe_crop, col = "black", fill = "grey90") +
    geom_sf(data = centroid_berlin, size = 6, pch = 22, linewidth = 3, fill = "red", col = "red") +
    geom_sf(data = centroid_berlin, col = "red", size = 4, pch = 22, fill = "grey90") +
    coord_sf(xlim = c(-15,30.1), ylim = c(35,55.1), expand = FALSE) +
    scale_x_continuous(breaks = seq(-15, 30, by = 15)) + 
    scale_y_continuous(breaks = seq(35, 55, by = 10)) + 
    theme(plot.background = element_rect(fill = "transparent", colour = NA))
)
```

## Combine both maps
```{r}
plot.with.inset <-
  ggdraw() +
  draw_plot(map_berlin) +
  draw_plot(eu_map, x = 0.54, y = .7, width = .3, height = .3)

plot.with.inset
```

# Final version (for now)
```{r}
plot.with.inset2 <-
  ggdraw() +
  draw_plot(map_berlin2) +
  draw_plot(eu_map2, x = 0.495, y = .68, width = .25, height = .25)

plot.with.inset2

# Save the plot
ggsave(filename = here::here("plots",
                             #"02_seasonal_activity",
                             "Study_area_SD2.tiff"),
       #width = 85,
      # height = 85,
      # units = "mm",
       dpi = 300)
```




***

<details><summary>Session Info</summary>

```{r sessionInfo}
## DO NOT REMOVE!
## We store the settings of your computer and the current versions of the
## packages used to allow for reproducibility
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>
