---
title: "traffic volume berlin 2009" ## name of your project
author: "Moritz Wenzler"                     ## your name(s)
date: "`r Sys.Date()`"                  ## current date
output:
  rmdformats::readthedown:
    code_folding: hide                  ## hide or show code by default?
    toc_depth: 3                        ## 3-level TOC
---

```{r setup, include=FALSE}
## You can ignore this chunk in most cases
## If you want to modify chunk options, you can do it here for all chunks or
## add the options in the repsective chunk header, e.g. `{r, message = FALSE}`
knitr::opts_chunk$set(echo = TRUE, warning = TRUE, message = TRUE,
                      fig.width = 9, fig.height = 6, dpi = 500, 
                      retina = 1, fig.showtext = TRUE)
```

* **Research question:**
* **Study area:**
* **Data:** 


# Setup

```{r packages}
sapply(list("sf", "tidyverse", "raster", "ows4R", "here"), 
       library, character.only = TRUE, logical.return = TRUE)

source(here("R", "download_fisbroker_metadata.R"))
```


# Data

```{r data}
gv <- st_read(here("data-raw", "berlin", "supply_green_areas_berlin_2016_3035",
                   "supply_green_areas_berlin_2016_3035.gpkg"))

berlin_district <- st_read(here("data-raw", "berlin", "berlin_districts_2020_3035", "berlin_districts_2020_3035.gpkg"))

temp_ras <- raster(here("data-proc", "berlin", "template_raster_berlin_10m_2020_3035", "template_raster_berlin_10m_2020_3035.tif"))

library(tmap)
tmap_mode("view")
tm_shape(gv) + tm_polygons() + 
  tm_shape(gv_ras) +  tm_raster(style = "cont",
            palette = terrain.colors(64))

# add numeric values for VOEFF_NAME column
gv2 <- gv %>% 
  mutate(VOEFF_NAME_num = case_when(
    is.na(VOEFF_NAME) ~ "NA",
    stringr::str_detect(VOEFF_NAME, "nicht versorgter Bereich") ~ "1",# set no supply on green area to 1
    stringr::str_detect(VOEFF_NAME, "schlecht versorgter Bereich") ~ "2",# set bad supply on green area to 2
    stringr::str_detect(VOEFF_NAME, "gering versorgter Bereich") ~ "3",# set low supply on green area to 3
    stringr::str_detect(VOEFF_NAME,"versorgter Bereich") ~ "4",# set good supply on green area to 4
    TRUE ~ as.character("NA"))
    ) %>% 
  mutate(VOEFF_NAME_num = as.numeric(VOEFF_NAME_num))

gv_ras <- fasterize::fasterize(sf = gv2,
                            raster = temp_ras,
                                   field = "VOEFF_NAME_num")

plot(gv_ras)

gv_ras[is.na(gv_ras)] <- 0

gv_ras_mask <- raster::mask(x = gv_ras, 
                                 mask = berlin_district,
                                 updatevalue = NA
                                 )
plot(gv_ras_mask)

create_meta_raster(gv_ras_mask, 
                   name = "supply_green_areas_berlin_raster_10m",
                   date = "2016",
                   epsg = "3035",
                   units = "0 - NA, 1 - no supply, 2 - bad supply, 3 - low supply, 4 - good supply",
                   descr = NA,
                   orig_source = read.csv(here("data-raw", "berlin", "supply_green_areas_berlin_2016_3035", "metadata_supply_green_areas_berlin_2016_3035.csv"), header = TRUE)$source,
                   data_source = here("data-raw", "berlin", "supply_green_areas_berlin_2016_3035",
                   "supply_green_areas_berlin_2016_3035.gpkg"),
                   d_down = NA,
                   mod = "NAs (zero values) inside Berlin borders where set to 0, VOEFF_NAME column changed to numeric values to column VOEFF_NAME_num",
                   path = "data-proc/berlin",
                   folder = TRUE)

writeRaster(gv_ras_mask, here("data-proc", "berlin", "supply_green_areas_berlin_raster_10m_2016_3035", "supply_green_areas_berlin_raster_10m_2016_3035.tif"), overwrite = TRUE)
```


***

<details><summary>Session Info</summary>

```{r sessionInfo}
## DO NOT REMOVE!
## We store the settings of your computer and the current versions of the
## packages used to allow for reproducibility
Sys.time()
#git2r::repository() ## uncomment if you are using GitHub
sessionInfo()
```

</details>
